### ISSUE TITLE
Bug Report: Grammatical errors

### ISSUE THREAD

**Issue by smrkarkii** [SauravMukherjee44/Aec-Library-Website#1003]
### Reproduction steps

I found it while scrolling over website. Please assign it to me under hacktoberfest.

### Expected behavior

It should be "Go to the "Choose and read books" section and search the book you are looking for ."

### Actual Behavior

![grammars](https://user-images.githubusercontent.com/58778838/194547981-0c08caab-510d-41c2-acd1-c413b00b1728.png)
It actually is ":Go to the "CHoose and read books" section and search the book you are looking for ."

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by ShalabhDevliyal** [comment]
I found it while scrolling over website. Please assign it to me under hacktoberfest.

**Comment by AK-codingmaniac** [comment]
Can I still work on this issue?

**Comment by IAmTamal** [comment]
> Can I still work on this issue?

Go ahead !

**Comment by IAmTamal** [comment]
@smrkarkii Go ahead

**Comment by smrkarkii** [comment]
Thank you. I am on it.

**Comment by Ayushbajpai19** [comment]
Hello, can i work on this issue please?
