### ISSUE TITLE
Better Visibility in Get In Touch Form

### ISSUE THREAD

**Issue by pranavgupta11** [SauravMukherjee44/Aec-Library-Website#1004]
Currently there is no clear visibility in the Get In Touch Form.
Before:
![image](https://user-images.githubusercontent.com/68846421/194564495-860350d3-39bc-4917-a338-171b5384e2f1.png)
After:
![image](https://user-images.githubusercontent.com/68846421/194565006-eb9761b2-4ead-4110-a9e9-648b4b15871d.png)

Please assign this to me and lebel it

**Comment by IAmTamal** [comment]
Go for it @pranavgupta11

**Comment by Satakshijain** [comment]
@SauravMukherjee44 can you assign this issue to me
