### ISSUE TITLE
Bug Report: Buttons are not working properly

### ISSUE THREAD

**Issue by AbhiPatel10** [SauravMukherjee44/Aec-Library-Website#1013]
### Reproduction steps

**Buttons are not working properly on some pages.**

When we click on some parts of the button, it doesn't respond to what we want, so there is some anchor tag misplacing issue, so I'm working on it. Please assign this task to me.

### Expected behavior

The button should work on clicking anywhere on the button.

![Screenshot 2022-10-08 163344](https://user-images.githubusercontent.com/76242769/194704291-3153caab-d961-4ee9-9a9f-1e5d431d4ee5.jpg)

### Actual Behavior

It only works when you click the text on the button. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by snehafarkya** [comment]
Hey! I would like to take this issue. Can you pls assign this to me?

**Comment by AbhiPatel10** [comment]
@SauravMukherjee44  Please assign this task to me and Give the tag of hecktoberfest.

**Comment by IAmTamal** [comment]
@AbhiPatel10 go for it !

**Comment by AbhiPatel10** [comment]
@IAmTamal #1040 Problem Solved Please Check and accept the Pull request
