### ISSUE TITLE
Bug Report: Spelling Mistake 

### ISSUE THREAD

**Issue by tushar54594** [SauravMukherjee44/Aec-Library-Website#1014]
### Reproduction steps

I was scrolling through the website and found out this mistake

### Expected behavior

It should be Go to our "Recommended Book" section. Choose your book which you want to download then click on the "Download as pdf". Happy reading :) "

### Actual Behavior

![Screenshot (597)](https://user-images.githubusercontent.com/94536522/194725724-ac367990-c29d-41f2-8391-4f53c7a2503c.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by tushar54594** [comment]
@SauravMukherjee44 @IAmTamal Please assign me this issue

**Comment by IAmTamal** [comment]
Go for it !

**Comment by tushar54594** [comment]
@IAmTamal By mistake you assigned @SauravMukherjee44 this issue
