### ISSUE TITLE
Bug Report: Instagram link is not working in the resources page

### ISSUE THREAD

**Issue by tushar54594** [SauravMukherjee44/Aec-Library-Website#1015]
### Reproduction steps

I was scrolling through the website and checking all the links when I found out this bug.

### Expected behavior

When we click on instagram icon in the resources page, it should direct us to the instagram page of the founder @SauravMukherjee44. 

### Actual Behavior

When we click on instagram icon  in the resources page, it should direct us to the instagram page of the founder @SauravMukherjee44 but it is directing again to the resources page only. 

![Screenshot (598)](https://user-images.githubusercontent.com/94536522/194726403-127dbeb3-1d87-45a8-bffb-3801e3784925.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by tushar54594** [comment]
@SauravMukherjee44 @IAmTamal Can you check this issue

**Comment by SauravMukherjee44** [comment]
Go for it!
For support join our discord community: https://discord.com/servers/codein-community-831388874118660156
