### ISSUE TITLE
Feature: Add more Notes about DSA

### ISSUE THREAD

**Issue by Nitya-Pasrija** [SauravMukherjee44/Aec-Library-Website#1024]
### Feature description

Have to add more pdf files to the Notes section, mostly abt DSA

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Nitya-Pasrija** [comment]
@SauravMukherjee44 can u assign this to me?

**Comment by SauravMukherjee44** [comment]
Go for it!
For support join our discord community: https://discord.com/servers/codein-community-831388874118660156
