### ISSUE TITLE
Adding class 8 books in NCERT section & improving.

### ISSUE THREAD

**Issue by Panda-Abhisek** [SauravMukherjee44/Aec-Library-Website#1025]
### Feature description

Updating the dummy books by the NCERT Books of class 8th
And improving the page.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Panda-Abhisek** [comment]
Hey @SauravMukherjee44, Please assign me to this issue.
I am working on it.
There are some issues with the website, but my work can fix them.

**Comment by SauravMukherjee44** [comment]
Go for it!
For support join our discord community: https://discord.com/servers/codein-community-831388874118660156

**Comment by Panda-Abhisek** [comment]
@SauravMukherjee44 raised a PR for issue #1025.

**Comment by Pheonix-001** [comment]
Hello, Could you please assign this issue to me.
I would love to work
