### ISSUE TITLE
Feature: Adding a book on Digital System Design [3rd year Btech]

### ISSUE THREAD

**Issue by arneja-arnav** [SauravMukherjee44/Aec-Library-Website#1026]
### Feature description

Adding a book on Digital System Design by Morris Mano. Would serve helpful to ECE Btech Students. Please assign this issue to me @SauravMukherjee44.

Could you approve this issue for hacktoberfest as well?

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by SauravMukherjee44** [comment]
Go for it!
For support join our discord community: https://discord.com/servers/codein-community-831388874118660156

**Comment by arneja-arnav** [comment]
@SauravMukherjee44 could you check this Pull Request above please?
