### ISSUE TITLE
Feature:  Adding curve to borders, enhancing user interaction

### ISSUE THREAD

**Issue by ritishbhardwaj** [SauravMukherjee44/Aec-Library-Website#1028]
### Feature description

Simple rectangular borders are boring.
Adding curves to the borders. Looking good

![WhatsApp Image 2022-10-10 at 02 22 50](https://user-images.githubusercontent.com/81488252/194779153-04e98521-c1c9-48c3-9d3b-f01ad9f474e0.jpg)

Before 

![WhatsApp Image 2022-10-10 at 02 23 42](https://user-images.githubusercontent.com/81488252/194779167-207a509a-1f8e-44ac-b700-1644e4947b2a.jpg)

After

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by ritishbhardwaj** [comment]
@SauravMukherjee44 
Assign this issue to me

**Comment by Yamini1406** [comment]
Hello. I'd love to work on this Issue. Please assign this to me

**Comment by Apocalyptic04** [comment]
Hi @IAmTamal I am beginner to open source in hacktober. Can you assign this feature to me? And add hacktober tag to it?

**Comment by ritishbhardwaj** [comment]
thanks to assign
