### ISSUE TITLE
Unnecessary Log out button in Login Page

### ISSUE THREAD

**Issue by devwithsubhrajit2002** [SauravMukherjee44/Aec-Library-Website#1038]
### Reproduction steps

On the login page, it is not necessary to have Log out button since No one can log out until logged in . After logging in then log out button should be provided. So i want ot remove that log out button from the login page. Please add hactoberfest tag to this issue and assign it to me.

Please can you add Hactoberfest tag on this issue for I am first in open source contribution.

### Expected behavior

![bug report in login page open source](https://user-images.githubusercontent.com/108873732/194821119-03af3997-3244-4b39-a10b-aff275dd8835.png)
Should not contain Log out button.

### Actual Behavior

Login page having log out button.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by devwithsubhrajit2002** [comment]
Hey @SauravMukherjee44 please assign me to this issue under Hactoberfest tag.

**Comment by IAmTamal** [comment]
Go for it

**Comment by VanshSrivastava** [comment]
can i contribute in this too?

**Comment by Muntabakhan** [comment]
can i contribute in this issue too?

**Comment by devwithsubhrajit2002** [comment]
Done @IAmTamal @SauravMukherjee44 this issue I have resolved.

**Comment by aditiii1103** [comment]
I would like to contribute to this issue under Hacktober tag
