### ISSUE TITLE
Improve the responsiveness of the play and highScore button for small devices.

### ISSUE THREAD

**Issue by surbhi400** [SauravMukherjee44/Aec-Library-Website#1056]
### Feature description

I want to improve the responsiveness of play button and highScore button for small devices.
![image(3)](https://user-images.githubusercontent.com/77582783/195249608-6310c2fe-7660-4b6e-8ca0-c25b575190cb.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by surbhi400** [comment]
@SauravMukherjee44 can you please assign me this issue under hactoberfest.

**Comment by SauravMukherjee44** [comment]
Go for it!
For support join our discord community: https://discord.com/servers/codein-community-831388874118660156
