### ISSUE TITLE
Bug Report: Your book section at index.html is not responsive

### ISSUE THREAD

**Issue by AbhiPatel10** [SauravMukherjee44/Aec-Library-Website#1062]
### Reproduction steps

![Screenshot 2022-10-12 162644](https://user-images.githubusercontent.com/76242769/195325480-6594e8c6-e291-43df-a22a-6d1205ceab74.jpg)

Your book section at Home page is not responsive.

@SauravMukherjee44, @IAmTamal 
Please assign this task to me. and give the hacktoberfest label. I'm Working on it.

Thanks & Regards
Abhi Patel

### Expected behavior

Should Responsive....

### Actual Behavior

Not Responsive.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by JatinSingh08** [comment]
Hey @AbhiPatel10, Can you please assign this issue to me. I would love to work on this.

**Comment by astitva0011** [comment]
hello, i would like to work on this issue. 
could you assign this issue to me?

**Comment by IAmTamal** [comment]
Go for it @AbhiPatel10

**Comment by AbhiPatel10** [comment]
@IAmTamal  Home Page Responsive Problem Solved Please Check and accept the Pull request #1072
