### ISSUE TITLE
Bug Report: Spelling mistake in FAQ's section

### ISSUE THREAD

**Issue by prakhar-1005** [SauravMukherjee44/Aec-Library-Website#1063]
### Reproduction steps

In the FAQ section, there is a spelling mistake and also the spacing between some of the words is not even.

![Screenshot (59)_LI](https://user-images.githubusercontent.com/94559623/195343254-5902fcf6-90fd-42ed-91cb-660d6804cfd3.jpg)

### Expected behavior

The spelling should be correct and spacing between words should be even.

### Actual Behavior

There is a spelling mistake in the line.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by geeky-hypertext629** [comment]
As this would be my first open source contribution ..I would like to request you to allow me to correct the spelling mistake and return back the corrected code as soon as possible.

**Comment by astitva0011** [comment]
hello, i would like to work on this issue. 
could you assign this issue to me?

**Comment by prakhar-1005** [comment]
@SauravMukherjee44 can you please take a look at the issue

**Comment by SauravMukherjee44** [comment]
@prakhar-1005 Go for it!
For support join our discord community: https://discord.com/servers/codein-community-831388874118660156
