### ISSUE TITLE
Color of the cards in Blogs page 

### ISSUE THREAD

**Issue by maneet057** [SauravMukherjee44/Aec-Library-Website#1087]
![image](https://user-images.githubusercontent.com/77922626/196469015-7cf11a2d-3bd2-4dd8-88bb-f9c4b92bb649.png)

The color of the cards in blog pages are white which can be changed to the color that will match with the background too. 

Please assign me this issue under Hacktoberfest

**Comment by creator79** [comment]
Is this issue is still available i will do this if its still opens

**Comment by anjaliSilawat** [comment]
I would like to work on this issue , please assign it to me
