### ISSUE TITLE
Bug Report: Text color in game.html in the quiz section needs update (Readability issue)

### ISSUE THREAD

**Issue by c-viswanath** [SauravMukherjee44/Aec-Library-Website#1112]
### Reproduction steps

When we play the quiz presented to us while the page loads, the color of the text of the question is Black which doesn't go well with the background causing problems in reading it. If we change the color or add a subtle light border to the text it would be much helpful.

### Expected behavior

It should have been a lighter color or there should have been a container around the question instead of transparent background.

### Actual Behavior

![image](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/87000253/4bf3be5d-2d6b-477e-b42e-5d4556f389f7)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by c-viswanath** [comment]
@SauravMukherjee44 I can help in fixing this issue and maybe adding a few UI improvements to the quiz page...Please assign me this issue

**Comment by karthiknadar1204** [comment]
I would like to work on this issue,please assign it to me

**Comment by sandeep0009** [comment]
hey i would like you assign me this issue i would like to work upon this under gssoc23

**Comment by SauravMukherjee44** [comment]
@sandeep0009 Go for it!

**Comment by c-viswanath** [comment]
![image](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/87000253/1eacf5bb-bd34-4a6b-afce-0b2bcf26acc0)

Has been resolved by blurring the background.
