### ISSUE TITLE
Bug Report:  Some Images are not visible

### ISSUE THREAD

**Issue by piyushkhurana2019** [SauravMukherjee44/Aec-Library-Website#1118]
### Reproduction steps

When i press on the resources option in the navigation bar, it took me to the resources section. Where i saw that some images are not visible 

### Expected behavior

The images should be visible

### Actual Behavior

Images are not properly linked due to which they are not visible

<img width="1440" alt="Screenshot 2023-05-20 at 8 03 43 AM" src="https://github.com/SauravMukherjee44/Aec-Library-Website/assets/96003210/ab72f8e2-ceaa-41de-9cce-1838b78df4d1">

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by 9520prashant** [comment]
Please Assign me  I will Fix this

**Comment by 9520prashant** [comment]
Hey @piyushkhurana2019 @praveenscience @Xaconi @eemike07 I have Fixed this issue Please Assign me so that I can make PR

https://github.com/SauravMukherjee44/Aec-Library-Website/assets/99237795/53a3d85d-a72d-487d-9604-7f1f827bb79c

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by 9520prashant** [comment]
> Please assign me this issue so that I can resolve it under GSSOC-23

I have fixed it bro

**Comment by 9520prashant** [comment]
Hey @praveenscience This issue has been fixed you can remove this from issue section.

**Comment by piyushkhurana2019** [comment]
@SauravMukherjee44, Sir i had raised this issue first and started working on it first. you assigned it so somebody else:(
