### ISSUE TITLE
Feature: Improving some UI

### ISSUE THREAD

**Issue by sumitkr2000** [SauravMukherjee44/Aec-Library-Website#1121]
### Feature description

Hey @SauravMukherjee44 I have previously contributed to your website during hacktoberfest and I have done important changes. This time also I am here for improving your website. I can see that the audio icon and footer are not properly aligned. Please assign me this issue so that I can fix it. Thank you!

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by sumitkr2000** [comment]
@adityavpawar bhai kuch aur karle kyu mere saare issue pe aake comment kr rha h???

**Comment by SauravMukherjee44** [comment]
@sumitkr2000 Go for it.

**Comment by khushi1711** [comment]
i want to work on this
