### ISSUE TITLE
Bug Report: Gap & Unwanted element below the Footer of the website 

### ISSUE THREAD

**Issue by abhayy143** [SauravMukherjee44/Aec-Library-Website#1123]
### Reproduction steps

I was checking the website throughly and found a bug that is if you scroll down till the footer of the website. There is a small space below the footer as shown in picture below. I found the same bug for other devices too. 

![12](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/53009878/e5208036-6170-4aa8-ba6d-adfcd1d63148)

![13](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/53009878/34e979fb-05d5-4d49-91af-19b0db100920)

### Expected behavior

There should be no spacing below the footer.

### Actual Behavior

There is a wide spacing and a small  element as well in below the footer. As you can see in the picture attached below.

![14](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/53009878/d0279bc2-0376-4b29-97da-fea44ac2e8e6)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by hindu-muppala** [comment]
@SauravMukherjee44 ,If any one no working ,I can solve this issue.
