### ISSUE TITLE
Bug Report: Footer is not responsive

### ISSUE THREAD

**Issue by SubhamB2003** [SauravMukherjee44/Aec-Library-Website#1125]
### Reproduction steps

The contributor section footer is not responsive.

### Expected behavior

Expected
![image](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/94003231/7c1714f5-2f0e-4143-bea4-5de3c3e8afad)

### Actual Behavior

You can check it out
![image](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/94003231/5c047797-0b31-4a13-a051-39da5e3d8239)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by SubhamB2003** [comment]
I would love to work on that. Please assign it to me under GSSOC 23.

**Comment by RahulRana701** [comment]
hi @SauravMukherjee44 I would like to work on this issue , can you assign it to me

**Comment by Sathvik902** [comment]
@SauravMukherjee44 , I would like to contribute to this issue as a part of @GSSOC'23
Please assign it to me. Thank you.

**Comment by SauravMukherjee44** [comment]
@SubhamB2003 Go for it.
