### ISSUE TITLE
Documentation:  Organising all the files in the repo properly.

### ISSUE THREAD

**Issue by Pin4sf** [SauravMukherjee44/Aec-Library-Website#1128]
## Making Codebase better.
There are many files in the repo which can be hard to **navigate** thus we need to maintain and organise all the files accordingly.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Hritik1503** [comment]
I am interested to work on this issue please assign me this task under gssoc.
