### ISSUE TITLE
Add alignments and responsiveness to Study Materials Section

### ISSUE THREAD

**Issue by riyasai22** [SauravMukherjee44/Aec-Library-Website#113]
I would like to add the following styling to the Study Materials Section.

* Uniformly allign the images with proper spacing.
* Add hover effects.
* Add responsiveness for tab and mobile devices.

![correction](https://user-images.githubusercontent.com/80235375/135709611-d5601cc3-17b6-4a67-a7dc-94cf1e017c37.png)

I would like to change it to this:
![png1](https://user-images.githubusercontent.com/80235375/135709646-78f53c51-0e19-4a1f-91f0-e7ade49b28ac.png)

**Comment by riyasai22** [comment]
I want to work on this issue. Please assign it to me.

**Comment by copyNinja1219** [comment]
hey I just improved the responsiveness of the images : ) . #122

**Comment by riyasai22** [comment]
Kindly look into my PR and let me know if any changes have to be made. @SauravMukherjee44
