### ISSUE TITLE
Improve UI by changing background color

### ISSUE THREAD

**Issue by Srija-Burugula** [SauravMukherjee44/Aec-Library-Website#1133]
### Feature description

The Background color is not very attractive. We can enhance the UI by changing the background color. Please assign me this issue.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by praduman8435** [comment]
@Srija-Burugula Assign this to me under GSSoC'23.

**Comment by trisharaj06** [comment]
I would like to work on this issue, please assign this to me
