### ISSUE TITLE
Bug Report: Improve Issue Form by Adding validation

### ISSUE THREAD

**Issue by Geeta259** [SauravMukherjee44/Aec-Library-Website#1143]
### Reproduction steps

![Screenshot (234)](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/75520947/0831cc48-89f1-47f4-850b-ca81d802d9ad)

As you can see book name field is empty and issue date not selected  still not showing any error direct jump into author field it's one of the kind of bugs which i would like to  resolve by adding proper validation in all the input fields under GSSOC'23

Also can improve UI  design of this form by adding some hover effect outside the fields if any error occurs.

@SauravMukherjee44  consider this issue  !

### Expected behavior

Proper validation of each field should be add when any kind of error occurs.
like input field blank , not selected any category , author  etc.

### Actual Behavior

.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by SauravMukherjee44** [comment]
You can go for it.
For any help, you can reach out to me here: https://sauravmukherjee.bio.link/
