### ISSUE TITLE
Improve UI of Search bar section of Contributors page

### ISSUE THREAD

**Issue by Geeta259** [SauravMukherjee44/Aec-Library-Website#1144]
UI of search bar section of contributors page can be improve by adding some CSS property more it can  be look more attractive and good!
@SauravMukherjee44 I would like to do under GSSOC'23 if you'll assign me!

**Comment by SauravMukherjee44** [comment]
@Geeta259 You can go for it.
For any help, you can reach out to me here: https://sauravmukherjee.bio.link/
