### ISSUE TITLE
qiuz background 

### ISSUE THREAD

**Issue by lakshmiprasannakusumanchi** [SauravMukherjee44/Aec-Library-Website#1147]
As we see the background of the qiuz section is little disturbing it is not clear in visibility of elements ,so I would like to work on this issue please assign it to me under gssoc'23

**Comment by trisharaj06** [comment]
I would like to work on this issue, please assign this to me

**Comment by Apreksha** [comment]
Hey @SauravMukherjee44, I'm a GSSoC'23 contributor and a full stack developer. I can enhance the UI of the quiz page. Could you please assign this task to me?

**Comment by PayalPadmalyaPrusty** [comment]
@SauravMukherjee44 I want to contribute.Please assign me
