### ISSUE TITLE
window.onload function has issue of Cannot read properties of null (reading 'style') (script.js:165) 

### ISSUE THREAD

**Issue by gautammali** [SauravMukherjee44/Aec-Library-Website#115]
script.js:165 Uncaught TypeError: Cannot read properties of null (reading 'style')
    at window.onload (script.js:165)

**Comment by Prashantsetia** [comment]
hi @gautammali , I have submitted the solution of this issue... Please accept PR and make me contributor too

**Comment by SauravMukherjee44** [comment]
@Prashantsetia Okay
