### ISSUE TITLE
Fix typos and grammatical errors

### ISSUE THREAD

**Issue by TunrayoIlawole** [SauravMukherjee44/Aec-Library-Website#1150]
There are a few typos and grammatical errors that I would like to fix.

I am a GSSoC'23 contributor and I would like to work on this. Kindly assign it to me.

Thank you.

**Comment by trisharaj06** [comment]
I would like to work on this issue, please assign this to me

**Comment by Apreksha** [comment]
Hey @SauravMukherjee44, I'm a GSSoC'23 contributor and a full stack developer. I can fix the typing and grammatical errors in the website. Could you please assign this task to me?

**Comment by SauravMukherjee44** [comment]
@TunrayoIlawole  Go for it.
For any support join our community: https://codeincommunity.com/
