### ISSUE TITLE
Feature: Implementing a better UI for the Login and Signup page 

### ISSUE THREAD

**Issue by Lobi29** [SauravMukherjee44/Aec-Library-Website#1151]
### Feature description

![11](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/108052802/3ae07bae-cca8-4551-a98d-b9e4c1a933d5)

### I will change the UI of the logIn/SignUp page to a better UI design, by looking at the requirements of the website.

Please assign this feature upgrade work to me, under @GSSOC2023

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Apreksha** [comment]
Hey @SauravMukherjee44, I'm a GSSoC'23 contributor and a full stack developer. I can enhance the UI of login and signup page and can also fix the minor issues. Could you please assign this task to me?
