### ISSUE TITLE
Feature: Add "Back to Top" Button on Content-Rich Pages

### ISSUE THREAD

**Issue by VSatwika** [SauravMukherjee44/Aec-Library-Website#1154]
### Feature description

- Several content-rich pages like blogs, contributors pages do not have 'back to top' button.
- Considering the abundance of content, it is crucial to include a convenient "Back to Top" button on these pages to enhance 
   user accessibility and ensure smooth scrolling to the page's beginning.

  I would like to work on this issue under GSSoc'23. Could you please assign this issue to me.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by SauravMukherjee44** [comment]
@VSatwika  Go for it.
For any support join our community: https://codeincommunity.com/

**Comment by rawalgeetika** [comment]
@SauravMukherjee44 Pls assign this task to me. I am a GSSOC contributor
