### ISSUE TITLE
Hover effects to the social media icon

### ISSUE THREAD

**Issue by ePSA-eJya** [SauravMukherjee44/Aec-Library-Website#1156]
### Feature description

Adding hover effects to the social media icon: enlarging and changing color.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Apreksha** [comment]
Hey @SauravMukherjee44, I'm a GSSoC'23 contributor and a full stack developer. I can add hover effects to the social media icons and enhance the appearance of the website. Could you please assign this task to me?

**Comment by SauravMukherjee44** [comment]
@ePSA-eJya  Go for it.
For any support join our community: https://codeincommunity.com/

**Comment by ePSA-eJya** [comment]
> @ePSA-eJya Go for it. For any support join our community: https://codeincommunity.com/

thanks......i'll surely join the community.

**Comment by abinash185** [comment]
I want to work on this issue . Please assign to me
