### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by 2024-SANDHYA** [SauravMukherjee44/Aec-Library-Website#116]
Will change the look of the landing page, by including proper background, about section & working on form alignment.

**Comment by SauravMukherjee44** [comment]
Hey, Do share some screenshots to view your changes and ideas.

**Comment by 2024-SANDHYA** [comment]
> 
> 
> Hey, Do share some screenshots to view your changes and ideas.

Sure!

**Comment by Drish-xD** [comment]
Hey @SauravMukherjee44 , I would Like to work on this. Could you Kindly assign it to me?

**Comment by SauravMukherjee44** [comment]
You can start working on it, No need for an assignment. create a PR.

**Comment by SauravMukherjee44** [comment]
@2024-SANDHYA Should I assign you ??

**Comment by Drish-xD** [comment]
Please review my PR #172

**Comment by 2024-SANDHYA** [comment]
> 
> 
> @2024-SANDHYA Should I assign you ??

Yes please, as I created the issue

**Comment by sowmiya-venkatesan** [comment]
Can you please assign me this issue?

**Comment by SauravMukherjee44** [comment]
@2024-SANDHYA Refer this design: https://www.behance.net/gallery/128585513/Library-Website-Design

**Comment by 2024-SANDHYA** [comment]
> 
> 
> @2024-SANDHYA Refer this design: https://www.behance.net/gallery/128585513/Library-Website-Design

I have some other designs in mind. I would like to work on that & I am referring behance only

**Comment by sowmiya-venkatesan** [comment]
@SauravMukherjee44 could you please make an active repo (1week) for design, so that people can contribute to that first, and then you can choose best out of it to proceed further!

**Comment by Pushti-R** [comment]
is this issue open ?
