### ISSUE TITLE
Add table of content

### ISSUE THREAD

**Issue by mhr1812** [SauravMukherjee44/Aec-Library-Website#1161]
### Feature description

I can add a table of content as mentioned below to readme.md for easy navigation, can you assign me this issue to me under GSSOC'23?
![tabofcontent](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/89465612/90486ea4-167f-4fb3-a4ce-512bfa8dc754)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by SauravMukherjee44** [comment]
@mhr1812 You can go for it.
For any help, you can reach out to me here: https://sauravmukherjee.bio.link/

**Comment by manoranjanonline** [comment]
I am interested to work on this issue please assign me this task under gssoc.
