### ISSUE TITLE
Update Navbar UI 

### ISSUE THREAD

**Issue by shubhanshurav** [SauravMukherjee44/Aec-Library-Website#1162]
### Feature description

![image](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/87806305/ffa439b4-3e78-445b-93e1-0134f4b6737b)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Hritik1503** [comment]
I am interested to work on this issue please assign me this task under gssoc.
