### ISSUE TITLE
Feature: Add relevant links in the FAQ section

### ISSUE THREAD

**Issue by TunrayoIlawole** [SauravMukherjee44/Aec-Library-Website#1168]
### Feature description

For example:
![Image](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/61794956/a0bf6d83-cbd5-4de3-b877-11982d75be67)

In the screenshot, we can add links to the resources, donate books and book issue sections.

I am a GSSoC'23 contributor and I would like to work on this. Kindly assign it to me.

Thank you.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by samsorrahman** [comment]
would you like to assign it to me @TunrayoIlawole

**Comment by SauravMukherjee44** [comment]
@TunrayoIlawole You can go for it.
For any help, you can reach out to me here: https://sauravmukherjee.bio.link/

**Comment by Hritik1503** [comment]
I am interested to work on this issue please assign me this task under gssoc.
