### ISSUE TITLE
Feature: Excessive scrolling on SignUp page

### ISSUE THREAD

**Issue by VSatwika** [SauravMukherjee44/Aec-Library-Website#1169]
### Feature description

- Unlike the login page, the sign up page has excess scrolling, which makes it difficult to navigate and view the content properly. 
- I have inspected the page's code, and it seems that the required container does not have the `overflow: hidden` property 
   applied.
  I would to resolve this issue. Could you assign this to me @SauravMukherjee44

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by SauravMukherjee44** [comment]
@VSatwika You can go for it.
For any help, you can reach out to me here: https://sauravmukherjee.bio.link/
