### ISSUE TITLE
Feature:  Improving Scrollbar design 

### ISSUE THREAD

**Issue by sharma21deepti** [SauravMukherjee44/Aec-Library-Website#1179]
### Feature description

I think the current design of scrollbar doesn't match with the website color code, So I want to improve the scrollbar. Please assign this task to me.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by manoranjanonline** [comment]
I am interested to work on this issue please assign me this task under gssoc.

**Comment by SauravMukherjee44** [comment]
@sharma21deepti You can go for it.
For any help, you can reach out to me here: https://sauravmukherjee.bio.link/

**Comment by manoranjanonline** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23
