### ISSUE TITLE
Footer of resource page need some improvement 

### ISSUE THREAD

**Issue by 9520prashant** [SauravMukherjee44/Aec-Library-Website#1182]
### Reproduction steps

You can the position of footer of resources page.

![Screenshot (247)](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/99237795/7ad6726d-ffcd-494a-8fe2-eb23a4110308)

### Expected behavior

It should looks like that.

![Screenshot (248)](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/99237795/e86bb5d9-a20f-44c9-9562-8158228f8457)

### Actual Behavior

Footer's position is not correct.

![Screenshot (247)](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/99237795/9866b755-106d-4c7a-bb38-b400cb46d7f8)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Hritik1503** [comment]
I am interested to work on this issue please assign me this task under gssoc.
