### ISSUE TITLE
[GSSoC'23] Formatting the DataTable on the home page

### ISSUE THREAD

**Issue by AdyaVerma03** [SauravMukherjee44/Aec-Library-Website#1185]
Please assign this to me.

**Comment by Hritik1503** [comment]
I am interested to work on this issue please assign me this task under gssoc.

**Comment by manoranjanonline** [comment]
i would like to work on it plz assign me

**Comment by AdyaVerma03** [comment]
### **Screenshots of all changes:**

Home page:
![Screenshot (344)](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/97099538/d2619cd8-3943-454f-b295-0b43581cbcfc)

Recommended books section:
![Screenshot (336)](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/97099538/8eea5ce2-aeb4-450e-9715-f669bb985e3b)

Audio books section:
![Screenshot (337)](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/97099538/c76ca215-d719-4ffe-ba11-e09ea3c84e97)

About Us page:
![Screenshot (338)](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/97099538/901f7971-0a80-47f2-b420-d8e39dfa9983)

Book donation form:
![Screenshot (340)](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/97099538/5565cc76-fba8-45c9-81eb-3886a7d2cd64)
![Screenshot (342)](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/97099538/48aa1ae9-b4de-4149-a149-16eecf86dc79)

Dialog box:
![Screenshot (334)](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/97099538/88b6deeb-48ff-40f3-8ff5-5d7cc38cb52c)
