### ISSUE TITLE
Feature: Improving readability/look of quiz/pages/game. {Gssoc'23}

### ISSUE THREAD

**Issue by SrishtiSonam** [SauravMukherjee44/Aec-Library-Website#1188]
### Feature description

quiz/pages/game =>

1. Putting the in question in a box to increase its readability.
2. Using other css to show the selected option and give more clarity.

<img width="618" alt="image" src="https://github.com/SauravMukherjee44/Aec-Library-Website/assets/113123593/8f0fcea4-313c-449e-9c52-6cfc48416f50">

Assign me this issue under gssoc'23.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by SauravMukherjee44** [comment]
@SrishtiSonam You can go for it.
For any help, you can reach out to me here: https://sauravmukherjee.bio.link/

**Comment by SrishtiSonam** [comment]
Thank you for providing this opportunity to me.
