### ISSUE TITLE
Inconsistent Nav Link Borders, Add Book Button, and Choose Book for Read Section Improvements

### ISSUE THREAD

**Issue by manaver** [SauravMukherjee44/Aec-Library-Website#1189]
The website requires several improvements to enhance its visual consistency and user experience. The following issues have been identified:

1. Inconsistent Nav Link Borders:
When hovering over the navigation links, the borders are currently inconsistent. To improve visual consistency, all nav link borders should be rounded by default when in the hover state.

2. Add Book Button:
The design of the "Add Book" button needs improvement. Currently, it may not be visually appealing or noticeable enough. Consider enhancing its design, such as using a contrasting color, adding an icon, or applying a hover effect, to make it stand out and encourage user interaction.

3. Choose Book for Read Section:
The "Choose Book for Read" section requires improvement. It may lack clarity or ease of use. Consider redesigning the section to provide a more intuitive and visually pleasing interface, making it easier for users to select a book for reading.

### Proposed Solution:
To address these issues and improve the website:

1. Make the nav link borders consistently rounded when in the hover state.

2. Enhance the design of the "Add Book" button to make it visually appealing and noticeable. Consider using a contrasting color, adding an icon, or applying a hover effect.

3. Redesign the "Choose Book for Read" section to improve clarity and usability. Create an intuitive and visually pleasing interface to facilitate the selection of books for reading.

Please assign this issue to me

**Comment by SauravMukherjee44** [comment]
@manaver You can go for it.
For any help, you can reach out to me here: https://sauravmukherjee.bio.link/

**Comment by manaver** [comment]
Ok😄
