### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by Gunjanrathore8178** [SauravMukherjee44/Aec-Library-Website#1190]
### Feature description

All the pages have different footers,please assign this issue to me I'll work on it

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by manoranjanonline** [comment]
All the pages have different footers,please assign this issue to me I'll work on it

**Comment by SauravMukherjee44** [comment]
@Gunjanrathore8178 All pages have different themes and accordingly different footers.
