### ISSUE TITLE
Enhance : Ui of Recommended  books section. 

### ISSUE THREAD

**Issue by Pragati-3003** [SauravMukherjee44/Aec-Library-Website#1197]
### Feature description

I would like to change the UI of the recommendation books section to make it more attractive. 
![IMG_20230525_102440](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/132778037/fcb5486a-c2fe-4fda-8fac-7f68bfeb9448)
I would like to make cards and add hover effects and also would like to change the background color. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by SauravMukherjee44** [comment]
You can go for it.
For any help, you can reach out to me here: https://sauravmukherjee.bio.link/

**Comment by Pragati-3003** [comment]
> You can go for it. For any help, you can reach out to me here: https://sauravmukherjee.bio.link/

Thanku for assigning this to me.
