### ISSUE TITLE
Enhance : Ui of listen to Audiobook. 

### ISSUE THREAD

**Issue by Pragati-3003** [SauravMukherjee44/Aec-Library-Website#1198]
### Feature description

I would like to change the UI of the listen to Audiobook section by applying hover effects, box shadow and cool backgrounds. Also I will like to make cards for the same. 
![IMG_20230525_102450](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/132778037/c320a4c7-89a5-4cd5-ae29-7de02cdb1d14)
So, please issue this to me. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by SauravMukherjee44** [comment]
You can go for it.
For any help, you can reach out to me here: https://sauravmukherjee.bio.link/

**Comment by Pragati-3003** [comment]
> You can go for it. For any help, you can reach out to me here: https://sauravmukherjee.bio.link/

Thanku for assigning this to me.
