### ISSUE TITLE
Add JS validation on donate books form

### ISSUE THREAD

**Issue by Geeta259** [SauravMukherjee44/Aec-Library-Website#1207]
### Feature description

I would like to work on this book donation form by adding JS validation on empty field and add some border effect on it.
Improve UI of submit and reset button also.

![Screenshot (268)](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/75520947/2ab86363-3c5e-463e-9bc1-ea860ef507ee)

like this:

![Screenshot (254)](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/75520947/fe4ddc26-6efb-47ae-96b3-90bc273fa5b3)

@SauravMukherjee44  please assign me this .

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by SauravMukherjee44** [comment]
You can go for it.
For any help, you can reach out to me here: https://sauravmukherjee.bio.link/
