### ISSUE TITLE
Feature: Add Interview Preparation Books in the Website

### ISSUE THREAD

**Issue by shubhanshurav** [SauravMukherjee44/Aec-Library-Website#1208]
## Interview preparation Books
- 1. Cracking The Coding Interview

![image](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/87806305/93df1956-09f4-4300-8c20-8500668e6c20)

- 2. Cracking The Tech Career

![image](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/87806305/3983bad3-99a3-4aee-a076-a0a792d6913d)

- 3. How to Answer the 64 Toughest Questions

![image](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/87806305/31583419-12ed-43d1-a825-e661f6cec133)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by SauravMukherjee44** [comment]
You can go for it.
For any help, you can reach out to me here: https://sauravmukherjee.bio.link/

**Comment by shubhanshurav** [comment]
- I have added above books , so please merge this pull request:  https://github.com/SauravMukherjee44/Aec-Library-Website/pull/1209
