### ISSUE TITLE
No mail window on clicking mail address

### ISSUE THREAD

**Issue by kadambari68** [SauravMukherjee44/Aec-Library-Website#1212]
### Feature description

When you click on the mail address a mailto window or Gmail should open where the user just has to type their concerns and the receiver's address is already written which is absent in the AEC  Library website 

![aec_issue](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/112871361/930451a8-2037-4495-9bc3-d45ea9cea503)

 Also on clicking on the phone number it should directly open the keypad with the number already typed or the option to make a call. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Hritik1503** [comment]
I am interested to work on this issue under GSSoC 2023 as a contributor

**Comment by vishalsingh2972** [comment]
solved this issue, can you please check and merge the PR #1276  @SauravMukherjee44
