### ISSUE TITLE
UI Improvement: Navigate Arrow icon should be on the top of the screen

### ISSUE THREAD

**Issue by crocmons** [SauravMukherjee44/Aec-Library-Website#1219]
### Reproduction steps

**"On your website, we need to move the navigation arrow icon from the bottom of the screen to the top, as it will enhance the UI/UX for users. Please assign me this task as a contributor for GSSOC23.**

![screenshot-aec-library-wbsite netlify app-2023 05 26-13_39_17](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/106610322/da03be2c-3e67-47b2-bd00-4ab38c90f08d)

### Expected behavior

![screenshot-netflixclone340 netlify app-2023 05 26-13_49_20](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/106610322/750950dd-e40e-4434-bd00-fd1c03ee54bf)

### Actual Behavior

The Navigate Arrow icon should be on the top of the screen so the users can easily navigate the main purpose here better UI.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Kapileswar-Moharana** [comment]
Assign this to me under GSSoC'23

**Comment by crocmons** [comment]
Please assign me this task as a contributor for GSSOC23.

**Comment by SauravMukherjee44** [comment]
@crocmons You can go for it.
For any help, you can reach out to me here: https://sauravmukherjee.bio.link/
