### ISSUE TITLE
AEC-Library Tag in Resource Page

### ISSUE THREAD

**Issue by 9520prashant** [SauravMukherjee44/Aec-Library-Website#1220]
### Reproduction steps

When I go to resource page I saw this issue you can see in Screen Shot.

![Screenshot (257)](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/99237795/f390d41d-209a-48a9-9a69-d8844c5ff5cc)

### Expected behavior

It should be look like that :

![Screenshot (258)](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/99237795/1fe6a9db-c193-41d9-9493-4aa528287acd)

Hey @SauravMukherjee44 I am contributor at GSSOC'23, Kindly assign this issue to me.

### Actual Behavior

it actually looks like that 

![Screenshot (257)](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/99237795/99fda3a8-753e-4e3a-b834-950d4bcbaa78)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by SauravMukherjee44** [comment]
You can go for it.
For any help, you can reach out to me here: https://sauravmukherjee.bio.link/

**Comment by 9520prashant** [comment]
Thanks
