### ISSUE TITLE
Bug Report:  There is a rectangle in the "Get in touch" card. [GSSoC'23]

### ISSUE THREAD

**Issue by 1Shubham7** [SauravMukherjee44/Aec-Library-Website#1240]
### Reproduction steps

There is a weird rectangle in the "Get in touch" card which doesn't look intentional and serves no purpose. It is looking very unprofessional.

![issuelab](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/116020663/0a34c983-672a-4471-96d9-6ea2129dda69)

### Expected behavior

Nothing happens in the backend but it is not looking good in the forntend

### Actual Behavior

That rectangle must be removed.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by 1Shubham7** [comment]
Please assign me this issue under GSSoC'23

**Comment by Hritik1503** [comment]
I am interested to work on this issue under GSSoC 2023 as a contributor
