### ISSUE TITLE
Audiobooks Play button

### ISSUE THREAD

**Issue by 9520prashant** [SauravMukherjee44/Aec-Library-Website#1241]
### Reproduction steps

when I play audiobook then the cursor not hover which is very wired thing.

https://github.com/SauravMukherjee44/Aec-Library-Website/assets/99237795/a704c615-a618-496b-8bd5-b78652e05735

### Expected behavior

it should have cursor pointer property then it looks good.

### Actual Behavior

it actually does not have cursor pointer property.

Hey @SauravMukherjee44 kindly assign this issue to me under gssoc.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by vishalsingh2972** [comment]
@9520prashant is this issue resolved if not I would like to work on it!
