### ISSUE TITLE
Books Icon position Issue

### ISSUE THREAD

**Issue by 9520prashant** [SauravMukherjee44/Aec-Library-Website#1243]
### Reproduction steps

When I go to ACE-Library then I saw the overflow of books icons. You can see in the video below: 

https://github.com/SauravMukherjee44/Aec-Library-Website/assets/99237795/bc3ea7a4-65ad-416f-8481-389aefc55f8f

### Expected behavior

It should looks something like that : 

https://github.com/SauravMukherjee44/Aec-Library-Website/assets/99237795/9675b79b-9143-4fae-ab26-1a4dddd698cd

### Actual Behavior

it actually has over margin in left side. Hey @SauravMukherjee44 kindly assign this issue to me under gssoc.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by SauravMukherjee44** [comment]
@9520prashant You can go for it.
For any help, you can reach out to me here: https://sauravmukherjee.bio.link/
