### ISSUE TITLE
Bug Report: Not responsive

### ISSUE THREAD

**Issue by abansal15** [SauravMukherjee44/Aec-Library-Website#1246]
### Reproduction steps

First i will find the code in the vs code studio then i will modify  the styling or will use media query to correct the bug

### Expected behavior

it should then become responsive and we will be able to see the word clearly and impresive way

### Actual Behavior

![image](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/120590200/452a4250-eb91-4df9-8e9b-c2059b8d4b99)
recommended is going out of the page

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by abansal15** [comment]
please assign this issue to me

**Comment by Tusar7684** [comment]
assign this to me
