### ISSUE TITLE
Bug Report: Improve responsiveness of 'Blogs' page

### ISSUE THREAD

**Issue by riddhigupta1110** [SauravMukherjee44/Aec-Library-Website#1249]
### Reproduction steps

For width less than 480px, the cards do not reduce in size to fit the entire card. Instead, a part of it cut and not visible.

### Expected behavior

The card size should reduce for width less than 480px as well so that the entire card is visible.

### Actual Behavior

![Blogs_Unresponsiveness](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/112184998/fa44eaad-8f3b-4d22-808a-6e0c699389f4)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by riddhigupta1110** [comment]
I can make the necessary changes to make the page responsive. Please assign this issue to me under GSSoC 23.

**Comment by SauravMukherjee44** [comment]
@riddhigupta1110 You can go for it.
For any help, you can reach out to me here: https://sauravmukherjee.bio.link/

**Comment by priyanshu942** [comment]
I'm a GSSoC contributor ..
I would like to work on this section...

would you please assign me to this task ??
