### ISSUE TITLE
Bug Report: Every page opens on a new tab

### ISSUE THREAD

**Issue by riddhigupta1110** [SauravMukherjee44/Aec-Library-Website#1251]
### Reproduction steps

Whenever we click on any button to lead us to a new page, it opens on a new tab.

### Expected behavior

Every new page shouldn't open on a new page. Opening every webpage of a website on a new tab can negatively impact user experience by cluttering the browser, confusing navigation, and requiring additional effort to manage multiple tabs.

### Actual Behavior

https://github.com/SauravMukherjee44/Aec-Library-Website/assets/112184998/953eb7f5-36cc-40a7-b1a2-1f0164c26a56

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by 9520prashant** [comment]
Hey @riddhigupta1110 I appreciate your effort but some website are opening their pages in new tab for example GeeksForGeeks

**Comment by CoderKaushik** [comment]
I would like to work on the issue, please assign it to me.

**Comment by priyanshu942** [comment]
I'm a GSSoC contributor ..
I would like to work on this section...

would you please assign me to this task ??
