### ISSUE TITLE
Read Book button issue

### ISSUE THREAD

**Issue by 9520prashant** [SauravMukherjee44/Aec-Library-Website#1260]
### Reproduction steps

When I got to Home page then Read Book button looks very wired you can it in SS.

![Screenshot (272)](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/99237795/e93725e8-6980-41fe-98de-ea75f157698d)

### Expected behavior

it needs improvement in styling , Hey @SauravMukherjee44 Kindly assign me this issue under Gsssoc.

### Actual Behavior

it actually looks like that because it has given wrong padding

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by 9520prashant** [comment]
Hello @Siddhant422 I have fixed it

**Comment by vishalsingh2972** [comment]
> Hello @Siddhant422 I have fixed it

@9520prashant please close this PR if issue has been fixed!
