### ISSUE TITLE
Bug Report: Fix Text in About Page

### ISSUE THREAD

**Issue by Sriparno08** [SauravMukherjee44/Aec-Library-Website#1270]
### Reproduction steps

I went to the About page and encountered a typo in the 'Why Use AEC Library' section.

![Screenshot 2023-05-30 203228](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/89148144/9a083d3c-b5af-4258-93a8-9b0f3c894825)

In the below sentence, the preposition 'by' is not the right one to use.

> The software has been designed to be flexible and user-friendly by librarians and media specialists.

### Expected behavior

The preposition 'by' needs to be changed to 'for'.

Hence, the sentence should be:

> The software has been designed to be flexible and user-friendly for librarians and media specialists.

### Actual Behavior

The sentence is using an incorrect preposition 'by'.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by vishalsingh2972** [comment]
solved in PR #1276 @SauravMukherjee44 can you please check and merge the PR

**Comment by vishalsingh2972** [comment]
solved in PR https://github.com/SauravMukherjee44/Aec-Library-Website/pull/1276 @SauravMukherjee44 can you please check and merge the PR
