### ISSUE TITLE
Image in Resources

### ISSUE THREAD

**Issue by 9520prashant** [SauravMukherjee44/Aec-Library-Website#1271]
### Reproduction steps

when i go to resources page and I saw this:

![Screenshot (275)](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/99237795/8a2d114d-8cd7-42f1-b689-c66f609c17af)

### Expected behavior

it should have an image in card. Hey @SauravMukherjee44 kindly assign me this issue under gssoc.

### Actual Behavior

it actually does not have any image.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by vishalsingh2972** [comment]
solved in PR #1276 @SauravMukherjee44 can you please check and merge the PR

**Comment by 9520prashant** [comment]
@vishalsingh2972 Bro Why you are raising PR Without assigning issue, hey @SauravMukherjee44 is it ok to raise a PR without assigning issue

**Comment by vishalsingh2972** [comment]
solved in PR https://github.com/SauravMukherjee44/Aec-Library-Website/pull/1276 @SauravMukherjee44 can you please check and merge the PR
