### ISSUE TITLE
Increase footer width 

### ISSUE THREAD

**Issue by Krishnapro** [SauravMukherjee44/Aec-Library-Website#130]
Hey , if you increase footer width then it will be looks good.

**Comment by Neeraj2002** [comment]
Heyy, I would love to do that!
Assign me the task

**Comment by omsali** [comment]
@SauravMukherjee44 Can I do this fix.

**Comment by SauravMukherjee44** [comment]
@omsali Yeah Sure, Create a PR!

**Comment by Neeraj2002** [comment]
@SauravMukherjee44 I didn't get a notification for the task assigned!
Just saw it
I fixed the issue and have sent you the PR

Sorry for the late reply.
