### ISSUE TITLE
BUG: Prompt user to fill in key fields on Book Add screen not working

### ISSUE THREAD

**Issue by chibitalex** [SauravMukherjee44/Aec-Library-Website#131]
Hi! The current version of the site does not appear to have any error catching text when a key field is not filled out (Title, Author). I want to add a prompt to let the user know that the fields are required instead of the item being failed to add and the book list not being updated.

EDIT: Upon further inspection, there is a feature like this, but it's just not working. Thus, this would actually be a bug fix.

**Comment by Sin-Sumit** [comment]
@SauravMukherjee44 let me work on this? Assign it to me.

**Comment by SauravMukherjee44** [comment]
@Sin-Sumit Go for it!
