### ISSUE TITLE
Upload new book

### ISSUE THREAD

**Issue by pilipi-puu-puu** [SauravMukherjee44/Aec-Library-Website#1335]
### Feature description

Want to add more books in the notes folder.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by muskanmandloi** [comment]
Please assign it to me
