### ISSUE TITLE
Feature: Resources webpage need UI improvement.

### ISSUE THREAD

**Issue by HimanshuNarware** [SauravMukherjee44/Aec-Library-Website#1336]
### Feature description

The Resources webpage need UI improvement.
##Screenshot
![218](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/83147410/b045e582-2b5b-42e2-b2a3-48e2f1a01d74)

![219](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/83147410/17f6cb7e-7f7f-4e26-9d74-3934edd79658)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by rohanbabbar04** [comment]
Can you elaborate what UI/styling improvement @HimanshuNarware ?

**Comment by HimanshuNarware** [comment]
> Can you elaborate what UI/styling improvement @HimanshuNarware ?

The content box need margin and the box styling, the content box is looking unattractive  and need styling ,Which can improve the UI of the page
