### ISSUE TITLE
Bug Report: New Tab opening on selection of the navbar items.

### ISSUE THREAD

**Issue by SVyusti** [SauravMukherjee44/Aec-Library-Website#1353]
### Reproduction steps

When I selected an item on the navbar from the homepage I found out this issue.

### Expected behavior

The route should be updated in the same tab as the homescreen, to prevent multiple tabs from opening.

### Actual Behavior

Currently in the homescreen on selection of any of the navbar menu item a new tab opens. This make it very inconvenient, all the others pages are working fine. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by rohanbabbar04** [comment]
Sure go ahead @SVyusti

**Comment by rohanbabbar04** [comment]
Already present #1251
