### ISSUE TITLE
Feature: Everytime click on navbar content it open newtab

### ISSUE THREAD

**Issue by HimanshuNarware** [SauravMukherjee44/Aec-Library-Website#1374]
### Feature description

Description
Every time when we click on the navbar content (like About, Blog, Resources) it opens a new tab that consumes more ram than a single page, I want to work on this issue, Also it affects the user experience.

##Video

https://github.com/SauravMukherjee44/Aec-Library-Website/assets/83147410/e0866be4-9214-429f-adb9-323ed1ae7bd7

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by rohanbabbar04** [comment]
Closing this
