### ISSUE TITLE
Feature: Improvement in the styling of the Home Page

### ISSUE THREAD

**Issue by crapbagaah** [SauravMukherjee44/Aec-Library-Website#1378]
### Feature description

I would like to contribute to this by changing the font of the entire website and making it more eye-catching. I would like to change the navbar hover effect as an underline would be preferable to the entire hover effect. Please assign me this issue under GSSOC'23.

![image](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/90127903/71357cde-ff68-448e-8afe-38071370a92e)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by rohanbabbar04** [comment]
I think this would be a very big issue can you create sub issues maybe one for hover effect, one for font @crapbagaah 
So I am closing this issue, you can create sub issues so that it is easy for us to track...
