### ISSUE TITLE
Important Feature: Add validation in Signup and Sign In form

### ISSUE THREAD

**Issue by Geeta259** [SauravMukherjee44/Aec-Library-Website#1379]
### Feature description

JS validation add in sign up, sign in form to enhance user experience
Now,  without any validation it submitting the form .
![Screenshot (429)](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/75520947/ae55d558-82f9-4936-b253-d56d3d45cdeb)
![Screenshot (430)](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/75520947/31603819-dc85-44d3-94b7-25fa91d61b65)

@SauravMukherjee44 @rohanbabbar04 I would like to  contribute on this project under  GSSOC'23

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by komalioruganti** [comment]
Can you assign me this issue under gssoc'23?

**Comment by rohanbabbar04** [comment]
Go ahead @Geeta259
