### ISSUE TITLE
[Bug Report]: all links in the navbar section opens a new page every time clicked 

### ISSUE THREAD

**Issue by trishanu-init** [SauravMukherjee44/Aec-Library-Website#1380]
### Reproduction steps

I found this bug while browsing this site and found out that it is really distracting and has to be resolved ASAP.

https://github.com/SauravMukherjee44/Aec-Library-Website/assets/85580785/bd38e715-ad8c-4369-b5fc-032769f3e927

### Expected behavior

It should remain on the same tab while a user browses around the website and the user should not have to navigate around to all the tabs to find the correct page.

### Actual Behavior

It should actually work like this....

https://github.com/SauravMukherjee44/Aec-Library-Website/assets/85580785/49980ef4-9da1-447c-9efd-e7cf4e1cc7fb

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by trishanu-init** [comment]
please assign this issue to me under gssoc23

**Comment by rohanbabbar04** [comment]
> please assign this issue to me under gssoc23

Go ahead @trishanu-init

**Comment by rohanbabbar04** [comment]
Already present #1251

**Comment by rohanbabbar04** [comment]
Closing this

**Comment by rohanbabbar04** [comment]
Closing this
