### ISSUE TITLE
Bug Report: Contact us at the bottom of the home page

### ISSUE THREAD

**Issue by PVBharadwaj** [SauravMukherjee44/Aec-Library-Website#1404]
### Reproduction steps

Contact us at the bottom of the home page appeared twice

### Expected behavior

Contact us at the bottom of the home page appeared twice. It should be corrected.

### Actual Behavior

<img width="956" alt="image" src="https://github.com/SauravMukherjee44/Aec-Library-Website/assets/117581755/357e31ea-40cd-4706-b1d9-e8494941760b">

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by PVBharadwaj** [comment]
@rohanbabbar04  please assign me this issue under Gssoc'23

**Comment by rohanbabbar04** [comment]
Thanks for spotting the bug ! 
Go ahead @PVBharadwaj, also align the social icons as well...
