### ISSUE TITLE
Bug Report: Missing email tag in about.html file

### ISSUE THREAD

**Issue by GauriBhandari** [SauravMukherjee44/Aec-Library-Website#1450]
### Reproduction steps

There is an issue in the about.html file where the email tag is missing, preventing users from easily contacting us for privacy-related inquiries or concerns.

Steps to Reproduce:

1. Open the about.html file.
2. Search for the email tag ( or [).](mailto:)
3. Notice that there is no email tag present in the file.

### Expected behavior

The about.html file should include an email tag to allow users to contact us regarding any matters.

### Actual Behavior

Upon inspecting the about.html file, it is observed that there is no email tag

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by GauriBhandari** [comment]
Hello @SauravMukherjee44 @rohanbabbar04 and team

I created this issue two days ago. Could someone please assign it or provide feedback? I'm eager to contribute and work on a solution.

Thank you!

**Comment by rohanbabbar04** [comment]
Can you share a ss where you wish to add it...

**Comment by GauriBhandari** [comment]
![Screenshot (823)](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/123401864/f0cd1588-0b3c-451b-b9fd-0b7872eccd7f)

**Comment by rohanbabbar04** [comment]
Ok got it 
I'll assign it to you...
