### ISSUE TITLE
Feature: Sticky Nav-bar

### ISSUE THREAD

**Issue by Manishak798** [SauravMukherjee44/Aec-Library-Website#1475]
### Feature description

You should consider adding a sticky nav bar as it will enhance your user experience because if users want to access a particular section they have to scroll down which leads to bad UX. 
We can do this using CSS3.
I want to work on this issue under GSSOC23, please assign it to me.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Manishak798** [comment]
Thank you @rohanbabbar04 , I will start my work upon it and will update you soon.

**Comment by rohanbabbar04** [comment]
> Hey @rohanbabbar04 as I have already started my work upon the assigned issue, I came across few bugs that reported as a new issue in the project, I am willing to work upon those too, kindly check my issues and please assign them to me under GSSOC23. Thank you.

Hi @Manishak798, As you are a new contributor to this project, I will assign them after you close this one. I will add the labels on your PR(as they are the ones which will count towards points).

**Comment by Manishak798** [comment]
No problem, @rohanbabbar04 , I will make my PR for this one.

**Comment by Manishak798** [comment]
Hey @rohanbabbar04 please check my PR and let me know.
Thank you.
