### ISSUE TITLE
Feature: navbar and footer not consistent across the pages

### ISSUE THREAD

**Issue by sumitkr2000** [SauravMukherjee44/Aec-Library-Website#1483]
### Feature description

Hey, @SauravMukherjee44 The navbar and footer are not consistent across the websites. Please assign me this issue. Thank you!

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Neha626177** [comment]
I would like solve this issue please assign me this issue
