### ISSUE TITLE
Fix the alignment of items on the Navbar. Increase Spaces

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#150]
![image](https://user-images.githubusercontent.com/72380920/135732763-e390e2d8-c6f5-426c-9f0b-3b33812add96.png)

**Comment by agarwalrashika00** [comment]
Hey! please assign this issue to me. I am confident that I'll be able to resolve the issue.

**Comment by harshita214** [comment]
Hey, I have solve this issue please look into it if there is something which needs to be done do tell

**Comment by pragyaSingh13** [comment]
hey @SauravMukherjee44  can you assign it to me as well, I'll do my best to fix this

**Comment by SauravMukherjee44** [comment]
@agarwalrashika00 @pragyaSingh13 Create a PR! No need of Assignment

**Comment by SauravMukherjee44** [comment]
@harshita214 Host your repository and share the link in the comment.

**Comment by harshita214** [comment]
https://github.com/harshita214/Aec-Library-Website

**Comment by harshita214** [comment]
is this the link you are talking about?
