### ISSUE TITLE
In the book donation page ...the heading is not visible

### ISSUE THREAD

**Issue by Anand4756** [SauravMukherjee44/Aec-Library-Website#168]
![book donation page](https://user-images.githubusercontent.com/73114463/135743919-5bb85478-2025-496a-9ed3-0cf4ff181630.PNG)

**Comment by Anand4756** [comment]
pls assign to me...

**Comment by Neeraj2002** [comment]
Heyy have completed the task
Just assign me and I will send the  PR

**Comment by copyNinja1219** [comment]
Hey @SauravMukherjee44 I just sent a pr #173 Please check : )
