### ISSUE TITLE
Upgrade the issue form templates, like in the GitHub beta issue templates.

### ISSUE THREAD

**Issue by Sin-Sumit** [SauravMukherjee44/Aec-Library-Website#181]
It will help maintainers to get a clear description of the problem.
@SauravMukherjee44 Please consider this.

**Comment by Sin-Sumit** [comment]
@SauravMukherjee44 Check this for the project. It add lot of value to the project
![screenshot (7)](https://user-images.githubusercontent.com/48879218/135794405-8dfe8ce5-37f1-446b-b4c0-e54fc0202155.png)

**Comment by Sin-Sumit** [comment]
@SauravMukherjee44 should I work on this?

**Comment by SauravMukherjee44** [comment]
Yeah Sure!

**Comment by Sin-Sumit** [comment]
Hey, @SauravMukherjee44 it will be good if it considers under hactoberfest. Please add hacktoberfest label so that it will be count

**Comment by Sin-Sumit** [comment]
Hey @SauravMukherjee44 to make this issue PR  count in the HF profile please add the Hacktoberfest-accepted label.
