### ISSUE TITLE
Header and Footer 

### ISSUE THREAD

**Issue by Sin-Sumit** [SauravMukherjee44/Aec-Library-Website#19]
The header should be changed, and the footer should be at the bottom of the page.

**Comment by Sin-Sumit** [comment]
assign me.

**Comment by Jaya3112** [comment]
I can make the header and footer more attractive and reliable to users.
Assign me .

**Comment by Jaya3112** [comment]
Assign me this issue.

**Comment by Sin-Sumit** [comment]
Hey, @Jaya3112 did you make any changes?

**Comment by Jaya3112** [comment]
hi,
@Sin-Sumit I am doing it.

**Comment by Sin-Sumit** [comment]
Ok, I have a suggestion, please visit few library sites and check out their header & footer.

**Comment by Jaya3112** [comment]
ok thankyou
If you named some of them then it will be helpful for me .

**Comment by Sin-Sumit** [comment]
@Jaya3112 I search few sites, but none of them have the same theme, So change according to your preferences.
And use the bootstrap CSS, like add the bootstrap class names.

**Comment by Jaya3112** [comment]
ok ,  thank you for your suggestion.

**Comment by ShreyaChopra13** [comment]
What changes need to be made in the header and footer?

**Comment by shubhankit123** [comment]
assign it to me

**Comment by Rathore-Devraj** [comment]
I would like to work on this ..please assign this to me!!

**Comment by sowmiya-venkatesan** [comment]
I would like to work on this issue

**Comment by SauravMukherjee44** [comment]
Change the alignment of Navbar and Footer elements
