### ISSUE TITLE
Navbar-issue

### ISSUE THREAD

**Issue by I-ArchanaDash** [SauravMukherjee44/Aec-Library-Website#194]
### donate-book.html
Following things are not accessible -
- Home page 
- contact us
### contact us .html
None of the pages (from navbar) are accessible from this web page .

**Comment by I-ArchanaDash** [comment]
I want to fix this . @SauravMukherjee44 Pls assign it tot me

**Comment by haaaziq** [comment]
Can i fix it? @SauravMukherjee44 @I-ArchanaDash
