### ISSUE TITLE
Change the UI of the Website

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#195]
- Multiple people can work.
- Design given Below.
- Link : https://www.behance.net/gallery/128585513/Library-Website-Design

**Comment by SauravMukherjee44** [comment]
Ui for reference: https://www.behance.net/gallery/128585513/Library-Website-Design?tracking_source=for_you_feed_user_published

**Comment by SauravMukherjee44** [comment]
Design Link - https://www.figma.com/file/wD7EOjKlTZqh3Yt9eZmPoB/ACELIBRARY_Landing-Page?node-id=1%3A2

**Comment by SauravMukherjee44** [comment]
![image](https://user-images.githubusercontent.com/72380920/135762934-291ea528-c7db-4557-8cb5-1082507e0b5e.png)

**Comment by SauravMukherjee44** [comment]
![image](https://user-images.githubusercontent.com/72380920/135762980-b0bb846e-3245-46cd-b4c2-ef7091cf12da.png)

**Comment by HetviSoni** [comment]
I would like to work on this issue.Could you please assign?

**Comment by SauravMukherjee44** [comment]
@HetviSoni You can start work on this.

**Comment by charlygg** [comment]
Is open for contribution?

**Comment by SauravMukherjee44** [comment]
@charlygg Yeah, Create a PR!

**Comment by tier3guy** [comment]
Hey Sourav I want to work on this issue can you please assign me this ?
