### ISSUE TITLE
Add Content to the About Page

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#206]

**Comment by PalakJain9** [comment]
Hey, I'd like to work on this and add meaningful content to the About page.
Kindly assign me this issue

**Comment by kambojshalabh35** [comment]
Hi, @SauravMukherjee44 I would like to work on it,
Add meaningful content and redesign the page.

**Comment by SauravMukherjee44** [comment]
@PalakJain9 You can start working on this.
