### ISSUE TITLE
The logo is different in different pages

### ISSUE THREAD

**Issue by Mansivjain00** [SauravMukherjee44/Aec-Library-Website#231]
The logo in the home page and about page is different. Similarly, it is different in the contact page. 

I could fix this this issue.

Please assign it to me

**Comment by Mansivjain00** [comment]
I could fix this issue.

**Comment by Mansivjain00** [comment]
Okay you have assigned someone to design a logo for the website, i'll work on this issue after thats ready?

**Comment by tier3guy** [comment]
Hey Mansiv, the logo is ready and it is present in the images folder as the name of ace.png and ace.svg . You can start your work.
