### ISSUE TITLE
Fix add Book Button

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#264]

**Comment by pratham-10** [comment]
Hello. I would like to work on this issue. Could you please assign it to me?

**Comment by SauravMukherjee44** [comment]
Fix it! The Js file.

**Comment by priyanshu688** [comment]
Can I work on this issue??

**Comment by Shofiya2003** [comment]
Hello,
Is this issue open for SWOC 2021 contributors? I would like to work on this issue. Thanks a ton.

**Comment by Shofiya2003** [comment]
Hey,
I checked the add Book button. It works fine, but the Edit button in the table does not work. Shall I raise an issue and then a PR to solve that issue. Thanks a ton.

**Comment by SauravMukherjee44** [comment]
Yes, Create a issue for that,I will assign that to you.
