### ISSUE TITLE
Entry-table-UI updated

### ISSUE THREAD

**Issue by ayushisingla** [SauravMukherjee44/Aec-Library-Website#310]
![image](https://user-images.githubusercontent.com/62255672/136264481-66fe82a7-b2a8-497a-82aa-86ec42cc8424.png)
I have already submitted a pull request.
I am new to open-source contributing and want to contribute to hacktoberfest to learn and participate.
pull-request -> #309

**Comment by SauravMukherjee44** [comment]
Update your repository
