### ISSUE TITLE
Latest blog section is empty

### ISSUE THREAD

**Issue by Amritanshu02** [SauravMukherjee44/Aec-Library-Website#317]
### Feature description

Want to add few demo blogs to the blog section.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by oneamanish** [comment]
see my pull req.
