### ISSUE TITLE
Feature: adding responsive contact us form and update design 

### ISSUE THREAD

**Issue by its-akashjha** [SauravMukherjee44/Aec-Library-Website#333]
### Feature description

I make responsive contact us form update design and navbar which looks user friendly.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Royal-Akash** [comment]
Hey @SauravMukherjee44 ! can you assign me this issue.
