### ISSUE TITLE
Bug Report: Login page is not responsive

### ISSUE THREAD

**Issue by Aryan-kumar-mains** [SauravMukherjee44/Aec-Library-Website#341]
### Reproduction steps

I will give a 100% width to login box and doing a flex-wrap to wrap , so that contents wrap or I can use media query

### Expected behavior

It should be responsive in small screen by taking 100% width and the welcome message is above the login title not in adjacent of the login box.

### Actual Behavior

Login page is actually not responsive , it takes 50% of width of the screen and the rest is taken by welcome message, due to this login text in login button squeezes .

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by SauravMukherjee44** [comment]
@Aryan-kumar-mains Go for it!
