### ISSUE TITLE
Bug Report: Resources page is not responsive 

### ISSUE THREAD

**Issue by Aryan-kumar-mains** [SauravMukherjee44/Aec-Library-Website#342]
### Reproduction steps

I'll make this responsive like cards in bootstrap using media queries

### Expected behavior

In small screen all the youtube contents or Question bank section will align vertically( like one above other).

### Actual Behavior

![Screenshot (177)](https://user-images.githubusercontent.com/52608321/136577846-4b556999-979b-4df7-a3db-622ce288c87f.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by md-jishan-ansari** [comment]
Please assign this issue to me I can definitely fix it.
