### ISSUE TITLE
Make the website responsive for mobile phone 🐱‍🏍

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#35]

**Comment by Rohan749** [comment]
Assign me @SauravMukherjee44

**Comment by Rohan749** [comment]
I have added some changes regarding this issue.
Do check it out :)

**Comment by rahulaarora** [comment]
Hey @SauravMukherjee44 
Can I work on this issue?
will optimize it for mobile view

**Comment by SauravMukherjee44** [comment]
@rahulaarora Yeah sure !

**Comment by rahulaarora** [comment]
@SauravMukherjee44 
made pr
do check
Rahulaarora/issue35 #114

**Comment by SauravMukherjee44** [comment]
@rahulaarora Site is not opening after merging. I had reverted your PR. Try to create a pr and add hosted link so that I can rev

**Comment by rahulaarora** [comment]
okay

**Comment by rahulaarora** [comment]
@SauravMukherjee44 now the site code is breaking due to other pr's merged in btw!
