### ISSUE TITLE
Change the design of Terms and Conditions page

### ISSUE THREAD

**Issue by barunipriyats** [SauravMukherjee44/Aec-Library-Website#350]
### Feature description

@SauravMukherjee44 I would like to change the UI design of Terms & Conditions page. I am good in designing web pages with HTML and CSS. I request you to assign this task to me.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by SauravMukherjee44** [comment]
@barunipriyats Go for it!
