### ISSUE TITLE
Adding Carosoule  question bank and study material section of resources section

### ISSUE THREAD

**Issue by shefali12-ab** [SauravMukherjee44/Aec-Library-Website#351]
### Feature description

Hii, I would like to contribute by adding a carousel card in the question bank and study material section. It will look good.
Looking forward for your reply.
Thank you.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by SauravMukherjee44** [comment]
@shefali12-ab Go for it!

**Comment by shefali12-ab** [comment]
Thank you :))

**Comment by shefali12-ab** [comment]
@SauravMukherjee44 I have made the required changes, please review it.
