### ISSUE TITLE
Bug Report:  Horizontal scroll bar appearing in the home page

### ISSUE THREAD

**Issue by Mansivjain00** [SauravMukherjee44/Aec-Library-Website#363]
### Reproduction steps

There is a horizontal scroll bar appearing in the home page. This spoils the responsiveness of the website and adds an extra section on the right side.

### Expected behavior

No horizontal scroll bar/ extra section on the right

### Actual Behavior

Horizontal scroll bar and extra section appearing on the right

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by asitsonawane** [comment]
Hello, I could fix this. Can you please assign me this issue under hacktoberfest?
