### ISSUE TITLE
Feature: Books Hover effect

### ISSUE THREAD

**Issue by Kyle-Symph** [SauravMukherjee44/Aec-Library-Website#397]
### Feature description

I would like to add a feature to add a effect when a user hovers on a book

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Abh1shekSingh** [comment]
@Kyle-Symph  I successfully resolved this issue. And made the Pull request @SauravMukherjee44  Please check once
