### ISSUE TITLE
Bug Report: Edit Button on the Home Page is not working

### ISSUE THREAD

**Issue by Shofiya2003** [SauravMukherjee44/Aec-Library-Website#494]
### Reproduction steps

Add a book to the list of 'Your Books'. Click the edit button. The information of book to be edited does not appear in the form.

### Expected behavior

The information of the book to be edited should reappear on the form. User should be able to edit the details and click the 'add book' button to edit the book.

### Actual Behavior

When the edit button is clicked the date of issue appears in the name column. When information is added a new book is added instead of editing the existing one.

![bug](https://user-images.githubusercontent.com/86974918/147460927-dbdd1745-2e50-4639-8a0a-f3c246051fce.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Shofiya2003** [comment]
Could you please assign me this issue?
Thank you

**Comment by SauravMukherjee44** [comment]
@Shofiya2003 Done.

**Comment by Shofiya2003** [comment]
I have solved the issue. Will create a pull request today.

**Comment by Shofiya2003** [comment]
Please review the pull request.
