### ISSUE TITLE
Add more resources/books to the library 

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#498]
### Description

Add more books, videos, questions, and contents to the Resource Page! 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by rohit465** [comment]
Hey Saurav,  I would like to work on this issue in resource page. 
For ex : Machine learning tutorials, Complete full stack web dev, and android dev youtube tutorials.

**Comment by codervivek5** [comment]
I want to work on this issue under JWOC

**Comment by whiteHatpro** [comment]
I want to work on this issue under JWOC

**Comment by SauravMukherjee44** [comment]
@whiteHatpro Go for it!

**Comment by whiteHatpro** [comment]
@SauravMukherjee44 done all the necessary changes
should i push the code?
