### ISSUE TITLE
Add Blogs to the featured blogs section

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#501]
### Description

![image](https://user-images.githubusercontent.com/72380920/148086018-d8f75436-4ce5-4c91-b0fd-c97f66148b29.png)

Add link to that blog too!

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by CAPTAINCOBRA** [comment]
Hi, can I try this issue?

**Comment by srini047** [comment]
Hey, I would like to work on this issue!!!
My previous blogs for reference:
> [Analytics Vidhya](https://www.analyticsvidhya.com/blog/author/srinikethcr7/)
> [dev.to](https://dev.to/hackthisfall/iris-dataset-implementation-2m7i)

Also can you mention on what Tech Stack the blogs have to be written??

**Comment by SauravMukherjee44** [comment]
It can be on any Technology.

**Comment by AbhinavBattu** [comment]
Please assign me this issue. I would like to work on it.

**Comment by Anish1411** [comment]
hey , i would like to work on this issue , assign it to me

**Comment by Siddhi-Mundada** [comment]
Please assign this issue to me.for GSSOC'22

**Comment by zugzwang03** [comment]
I would like to work on this issue under GSSOC'22

**Comment by Aman16-ai** [comment]
Can i work on it under gssoc22

**Comment by HarshKumarChoudary** [comment]
I would like to work on it. Please assign it to me.

**Comment by Abhisharma85** [comment]
Hey, I would like to work on this issue. Please assign it to me.
