### ISSUE TITLE
Add more questions to the FAQ section

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#502]
### Description

Add more questions to the FAQ section

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by 9Shalini** [comment]
I would like to work on this issue, please assign it to me @SauravMukherjee44

**Comment by PranK14** [comment]
i would like to work on this issue @jwoc

**Comment by codervivek5** [comment]
I want to work on this issue under JWOC

**Comment by 1ananya3** [comment]
I want to add some questions.Can you assign it to me?

**Comment by Khushi-Mattu** [comment]
I would like to work on this issue under GSSOC'22

**Comment by Sandhya312** [comment]
I wanted to add some useful questions. So please assign this issue to me under GSSOC'22.

**Comment by codervivek5** [comment]
I want to work on this issue under Gssoc'22

**Comment by Anshika-Srivastava** [comment]
@1ananya3 you have been assigned the issue. You can start working on it.

**Comment by 1ananya3** [comment]
> @1ananya3 you have been assigned the issue. You can start working on it.

Okay Thank you @Anshika-Srivastava . I am starting my work.
