### ISSUE TITLE
Improve the design of contact us page

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#504]
### Feature description

![image](https://user-images.githubusercontent.com/72380920/148086756-7242dc41-0e14-4355-9175-7ed684c0af35.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Yash-RajSingh** [comment]
I would like to work on this issue under SWOC'21. Kindly please assign this to me
