### ISSUE TITLE
Change the UI of the FAQ section.

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#511]
### Description

![image](https://user-images.githubusercontent.com/72380920/148541832-48ff456c-f5b7-42f7-a94f-9c1a26fe8b6d.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by AmanRana10** [comment]
I would like to work on this issue.

**Comment by Abdullah-Irfan-web** [comment]
Hello @AmanRana10 ,are you working on this issue

**Comment by AmanRana10** [comment]
Yes I am working on this issue

**Comment by SauravMukherjee44** [comment]
Any updates or i will unassign you?

**Comment by AmanRana10** [comment]
Sorry was not able to finish it
