### ISSUE TITLE
Create a Contributors page for the website

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#512]
### Description

Create a Contributors page for the website and add each contributor with their image and Github profile.
Link the page with the home page and add it to the navbar.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Abdullah-Irfan-web** [comment]
Hello @SauravMukherjee44 can i make this page?

**Comment by SauravMukherjee44** [comment]
Sure!
