### ISSUE TITLE
Improve the UI of the Blogs Section

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#523]
### Feature description

![image](https://user-images.githubusercontent.com/72380920/151842931-e9c70ff9-fe25-4508-86d0-9cd5d28de08e.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Tess-Vanta** [comment]
I want to work on this issue under JWOC

**Comment by Jyoti6828** [comment]
I want to work on this issue under JWOC. Kindly Assign it to me.

**Comment by tanya-gupta25** [comment]
I want to work on this issue under JWOC.

**Comment by tanya-gupta25** [comment]
I want to work on this issue under JWOC.

**Comment by SauravMukherjee44** [comment]
@Tess-Vanta Go for it! You have 4 days of time for Medium Level Issues.

**Comment by Tess-Vanta** [comment]
> @Tess-Vanta Go for it! You have 4 days of time for Medium Level Issues.

Thanks!!

**Comment by codervivek5** [comment]
I want to work on this issue under JWOC
