### ISSUE TITLE
Add Videos to the Resource Page and Categories the Videos using different labels 

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#524]
### Feature description

![image](https://user-images.githubusercontent.com/72380920/151843857-4f575246-cf99-42d6-ac43-24a56849c1b4.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Jyoti6828** [comment]
I want to work on this issue under JWOC. Kindly Assign it to me.

**Comment by SauravMukherjee44** [comment]
@Jyoti6828 Go for it! You have 2days of time for an Easy level Issues.

**Comment by Nidhi1k** [comment]
I want to contribute to it
