### ISSUE TITLE
Create a Newsletter Service for the Website

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#525]
### Feature description

![image](https://user-images.githubusercontent.com/72380920/151844234-14d4591c-56e1-46cb-bd7c-2255a20bd925.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by navyagarwal** [comment]
I would like to work on this issue under JWOC.

**Comment by SauravMukherjee44** [comment]
@navyagarwal Go for it! You have 1 week of time for the Hard level issues.

**Comment by codervivek5** [comment]
I want to work on this issue under JWOC

**Comment by AtriSukul1508** [comment]
I would like to contribute to this issue under JWOC

**Comment by Jyoti6828** [comment]
I want to work on this issue under JWOC.

**Comment by codervivek5** [comment]
I want to work on this issue under JWOC.
i also want to work in this issue.
