### ISSUE TITLE
Improve the Design of Contact Us Page 💻

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#526]
### Feature description

![image](https://user-images.githubusercontent.com/72380920/151846106-14049e70-ca25-4e30-9bec-80e068c55164.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Yash-RajSingh** [comment]
Hey @SauravMukherjee44, I was previously assigned to work on this issue and i did some work but then my final exams started so i couldn't finish my work. Sorry that i couldn't update you on the status. If its okay could you assign this issue to me and would it be okay if I could submit my work on 4th Feb

**Comment by SauravMukherjee44** [comment]
@Yash-RajSingh you can directly create a PR.

**Comment by combatantash** [comment]
I want to work on this issue under JWOC

**Comment by Ankit62042** [comment]
I want to work on this issue

**Comment by ishitaac** [comment]
"I want to work on this issue under JWOC"

**Comment by AtriSukul1508** [comment]
I would like to work on this issue

**Comment by SauravMukherjee44** [comment]
@ishitaac Go for it!
