### ISSUE TITLE
Make the UI more responsive and interactive for Mobile Phones 📱

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#527]
### Feature description

Make the UI more responsive and interactive for Mobile Phones 📱

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Ankit62042** [comment]
Hii, I want to work on this issue

**Comment by codervivek5** [comment]
I want to work on this issue under JWOC

**Comment by Shruti025** [comment]
Hey I would love to work on this issue under JWOC

**Comment by SauravMukherjee44** [comment]
@Shruti025 Go for it!

**Comment by Shruti025** [comment]
hey @SauravMukherjee44 really sorry for going over the alloted time limit. I am almost done with the changes. Is it possible to reassign the issue?

**Comment by Shruti025** [comment]
I will definitely make a PR by tomorrow. I hope you understand

**Comment by Shruti025** [comment]
I will surely make a PR by tomorrow morning. Hope you understand @SauravMukherjee44

**Comment by SauravMukherjee44** [comment]
Go ahead!

**Comment by Shruti025** [comment]
Thank you so much :)
