### ISSUE TITLE
Improve the UI of the Resource Page 💻

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#529]
### Feature description

![image](https://user-images.githubusercontent.com/72380920/151847280-4e450229-e74c-496d-a65a-2f076d92df95.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by navyagarwal** [comment]
I would like to work on this issue under JWOC.

**Comment by AtriSukul1508** [comment]
I want to contribute on this issue under JWOC

**Comment by SauravMukherjee44** [comment]
Go for it!
