### ISSUE TITLE
Implement the Use of Search Book Button 🔎

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#530]
### Feature description

![image](https://user-images.githubusercontent.com/72380920/151848090-570d2c29-c675-41b4-a46d-212c853d1415.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Daffodilgithub** [comment]
I want to work on this issue under JWOC

**Comment by codervivek5** [comment]
I want to work on this issue under JWOC

**Comment by Daffodilgithub** [comment]
What language do you recommend for solving this issue?

**Comment by SauravMukherjee44** [comment]
Javascript

**Comment by SauravMukherjee44** [comment]
You can take another issue if you unable to complete this

**Comment by Daffodilgithub** [comment]
As I am a beginner I am facing problems to solve it .Will you please  provide me some resources ?

**Comment by Daffodilgithub** [comment]
I prefer to work on html issues.

**Comment by SauravMukherjee44** [comment]
Okay, I Unassigned this issue. Work on Issue #538

**Comment by Daffodilgithub** [comment]
Ok thank you!

**Comment by tanya-gupta25** [comment]
I want to work on this issue under JWOC

**Comment by SauravMukherjee44** [comment]
@tanya-gupta25 Go for it!

**Comment by Devmindtk** [comment]
I would like to work on this issue.Please assign it to me.

**Comment by Devmindtk** [comment]
We have to search books from your books table?

**Comment by SauravMukherjee44** [comment]
Yes

**Comment by Devmindtk** [comment]
@SauravMukherjee44 
Actually i have a doubt after searching book and get find from table then what to do next?

**Comment by Devmindtk** [comment]
https://user-images.githubusercontent.com/91221069/153055292-c8ae3ed1-398a-46d5-ab62-b898873ce93d.mp4

check this final one @SauravMukherjee44

**Comment by SauravMukherjee44** [comment]
Great, Create a PR!

**Comment by Devmindtk** [comment]
> Great, Create a PR!

okay
