### ISSUE TITLE
Improve the UI and reduce the Loading time of Contributors Page ✨

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#531]
### Feature description

![image](https://user-images.githubusercontent.com/72380920/151848405-9dd85324-ec8a-4513-a1d7-abe9193ca27c.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by raxvab** [comment]
I want to work on this issue under JWOC

**Comment by codervivek5** [comment]
I want to work on this issue under JWOC

**Comment by SauravMukherjee44** [comment]
@raxvab Go for it!

**Comment by SauravMukherjee44** [comment]
You have one day to complete it, after that you will be unassigned!

**Comment by tusharjain365** [comment]
I want to work on this under JWOC

**Comment by SauravMukherjee44** [comment]
@tusharjain365 Go for it!
