### ISSUE TITLE
Design Graphics and arts for the Library Website

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#532]
### Feature description

Share your art by creating a Pull request.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by manya0210** [comment]
Hey!! I want to work on this issue under JWOC

**Comment by codervivek5** [comment]
I want to work on this issue under JWOC

**Comment by MadamChetnaSingh** [comment]
I want to work in this issues, pls tell me little bit more details.

**Comment by SauravMukherjee44** [comment]
@codervivek5 Go for it!

**Comment by SauravMukherjee44** [comment]
You have one day to complete a easy level issue.

**Comment by ronitblenz** [comment]
Hi, I want to take this issue

Thanks

**Comment by SauravMukherjee44** [comment]
You can design arts related to our Library

**Comment by ronitblenz** [comment]
Sure, am willing to do so
