### ISSUE TITLE
Feature: Adding more social icons in footer in contact us page

### ISSUE THREAD

**Issue by mgjain9871** [SauravMukherjee44/Aec-Library-Website#535]
### Feature description

Currently, only LinkedIn and GitHub social icons are present in the footer, I will add YouTube and Twitter social icons in the footer section of the Contact Us page.

![image](https://user-images.githubusercontent.com/71882225/151866660-da84fd6f-6799-4d81-976d-4eca03d88068.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by mgjain9871** [comment]
I want to work on this issue under JWOC.

**Comment by ishitaac** [comment]
"I want to work on this issue under JWOC"

**Comment by SauravMukherjee44** [comment]
The person who will create a issue, I will assign that to him/her.

**Comment by SauravMukherjee44** [comment]
@mgjain9871 Go for it! You have 2 days to complete a easy level issue.

**Comment by codervivek5** [comment]
I want to work on this issue under JWOC
