### ISSUE TITLE
Add more Questions and Answers in a detail to the FAQ Section.

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#536]
### Feature description

![image](https://user-images.githubusercontent.com/72380920/151938193-2fa1c4b0-9595-44ef-a2b5-b398654ab320.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by aditi-gosain** [comment]
I would like to work on this issue under JWOC.

**Comment by SauravMukherjee44** [comment]
@aditi-gosain Go for it! you have 1 day to complete it.
