### ISSUE TITLE
Improve  the Navbar of About Page 

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#537]
### Feature description

![image](https://user-images.githubusercontent.com/72380920/151938595-7f166fa1-1be5-4117-a9ed-3f9223ba1729.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by unnikrishnan2002** [comment]
Can I work on that under JWOC ?

**Comment by lishakothari** [comment]
I want to work on this issue under JWOC

**Comment by maneet057** [comment]
I would like to work on it under jwoc

**Comment by SauravMukherjee44** [comment]
@maneet057 Go for it!

**Comment by ishitaac** [comment]
I would like to work on this issue under JWOC
