### ISSUE TITLE
Improve the Footer of the About Page

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#538]
### Feature description

Improve the Footer of the About Page

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by mdsimar1901** [comment]
hey can I do that!

**Comment by SauravMukherjee44** [comment]
Under JWOC ?

**Comment by SauravMukherjee44** [comment]
@PrajwalDhule Go for it!

**Comment by Daffodilgithub** [comment]
I want to work on this issue under JWOC.
