### ISSUE TITLE
Create a Backend service for Donate Book page and store the data entered by the user.

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#539]
### Feature description

Data Should be sent to this email: mesouravofficial@gmail.com

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by dilroseR** [comment]
Can I use flask-python for this? @SauravMukherjee44

**Comment by SauravMukherjee44** [comment]
You can use either PHP or Node.

**Comment by dilroseR** [comment]
> You can use either PHP or Node. Since most of the contributors are familiar with these.

So is a database created already for storing?

**Comment by SauravMukherjee44** [comment]
No, It is not created yet.

**Comment by SauravMukherjee44** [comment]
Updates?

**Comment by dilroseR** [comment]
> Updates?

Kindly assign the issue to someone else. Got stuck with some other problem.

**Comment by Bijit-Mondal** [comment]
Can I get the issue to work with
