### ISSUE TITLE
Improve the UI of Donate Book Page 💻

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#541]
### Feature description

![image](https://user-images.githubusercontent.com/72380920/151939469-b4ae3771-4e97-473c-9c97-424f587f5ee6.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by SauravMukherjee44** [comment]
@Nidhi1k go for it!

**Comment by Nidhi1k** [comment]
Thanks

**Comment by tanya-gupta25** [comment]
I want to work on this issue under JWOC.

**Comment by maneet057** [comment]
I would like to work on it under jwoc

**Comment by SauravMukherjee44** [comment]
@maneet057 Go for it!
