### ISSUE TITLE
Add Technical Courses in the Resource Page of the Library 

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#545]
### Feature description

It can redirect users to another platform.
![image](https://user-images.githubusercontent.com/72380920/151992800-2bdfa71a-1d10-483b-9e8a-2c9dd17471c4.png)

Remove these and add courses in the course section.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Srijita-Mandal** [comment]
Hii, I want to work on this issue under JWoC

**Comment by SauravMukherjee44** [comment]
@Srijita-Mandal Go for it! Remove these videos from the course section and add courses with proper thumbnail and description. Your course thumbnail can redirect users to other platforms to complete the course.
