### ISSUE TITLE
Bug Report: About Us page and Donate Books Page have Search field which is unnecessary .

### ISSUE THREAD

**Issue by SSaurabhsahuu** [SauravMukherjee44/Aec-Library-Website#551]
### Reproduction steps

Click About in Home navbar
click Donate Books in Home Navbar

### Expected behavior

Search Field should not be displayed in Navbar

### Actual Behavior

Search Field is displayed in Navbar

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by SSaurabhsahuu** [comment]
Please assign this issue to me

**Comment by SauravMukherjee44** [comment]
@SSaurabhsahuu Go for it!
