### ISSUE TITLE
Create a section for Audio Books in the Home page below the recommended book section

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#559]
### Feature description

Create a section for Audio Books on the Home page below the recommended book section and add audio Books.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by JaynouOliver** [comment]
I can do this, please assign this work to me. (Question: what audiobooks should I add ?)
