### ISSUE TITLE
Create audio book section the resource page and add audio books 🔉

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#560]
### Feature description

Create audio book section the resource page and add audio books 🔉

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by AtriSukul1508** [comment]
I want to contribute to this issue under JWOC
