### ISSUE TITLE
Add Title and description about each image in the latest Blogs section.

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#561]
### Feature description

![image](https://user-images.githubusercontent.com/72380920/152314249-6dcb7911-cd19-4fd1-824f-38d729a3aed0.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by JaynouOliver** [comment]
I can do this easily, please assign this work to me!

**Comment by VaishnaviNigam25** [comment]
I want to work on this under JWOC @SauravMukherjee44  please assign to me

**Comment by SauravMukherjee44** [comment]
@VaishnaviNigam25 Go for it!
