### ISSUE TITLE
Add new features to the Library According your Ideas.

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#562]
### Feature description

Add new features to the Library According to your Ideas. 🔔

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Jyoti6828** [comment]
Can I try to add a slider for this section?
Like we can add some more tutorials and add a horizontal slider.

 
![image](https://user-images.githubusercontent.com/78480983/152322039-e5217294-201f-490c-b64f-cac2b9d0e781.png)
