### ISSUE TITLE
Create a Blogs page and Link it to the Home Page 🧑‍💻

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#563]
### Feature description

You need to create the blogs page from scratch and add some blogs in it.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by ishitaac** [comment]
I want to work on this issue under JWOC.

**Comment by Jyoti6828** [comment]
I want to work on this issue under JWOC. Please assign it to me.

**Comment by SauravMukherjee44** [comment]
@ishitaac Go for it! Quite tough competition 🥲

**Comment by ishitaac** [comment]
thank you!

**Comment by Jyoti6828** [comment]
I want to work on this issue under JWOC.

**Comment by SauravMukherjee44** [comment]
@Jyoti6828 Go for it!

**Comment by HarshKumarChoudary** [comment]
I would like to work on it for GSSOC 22. If its available then please assign it to me.
