### ISSUE TITLE
adding drop down list of authors 

### ISSUE THREAD

**Issue by ShlokMohanty** [SauravMukherjee44/Aec-Library-Website#58]
we can add some already popular or famous authors if the user is being confused which books to choose or may have forgotten the exact name of the book.

**Comment by AsfandToor** [comment]
Correct me if I am wrong, a list of author should be displayed by suggestions when the user types here?
![image](https://user-images.githubusercontent.com/76124914/134628466-64078372-c8d0-44fa-b70a-18f1cfccaded.png)

**Comment by ShlokMohanty** [comment]
@AsfandToor that should be the alternative you mean to say if suppose we take author rutherford the just writing the ruth would just show us the list of the authors right?

**Comment by SauravMukherjee44** [comment]
@ShlokMohanty Are you interested in this Issue?

**Comment by ShlokMohanty** [comment]
@SauravMukherjee44 yes sure you can consider me for this thing .Wil do it and solve it as soon as possible

**Comment by SauravMukherjee44** [comment]
Assigned ! Good luck.

**Comment by ShlokMohanty** [comment]
@SauravMukherjee44 thank you

**Comment by ShlokMohanty** [comment]
@SauravMukherjee44 which type of authors should we add to the list ? for example : novels , or other kind of story books
or also should we add the authors for programming books as well ?

**Comment by ShlokMohanty** [comment]
@SauravMukherjee44 i had a small doubt regarding this AECLibrary so basically it is like the book we are issuing we are adding the name and the authors name into the required columns right only the book we issued only its inofrmation will be written down on the Authors and Books section ?

**Comment by shubhankit123** [comment]
can u assign it to me

**Comment by ShlokMohanty** [comment]
@shubhankit123 i was working on this issue.You can try onther issues maybe?
