### ISSUE TITLE
Redesign Feedback section 

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#580]
### Feature description

![image](https://user-images.githubusercontent.com/72380920/152692361-254d13ee-cd0c-4c44-91d4-7bf56835a63b.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Priiyaa** [comment]
I would like to work on this under JWOC

**Comment by SauravMukherjee44** [comment]
Go for it!

**Comment by Priiyaa** [comment]
Hi!
Can you please elaborate what kind of UI you want for the feedback section?

**Comment by SauravMukherjee44** [comment]
It's totally upon your creativity, Just match the theme of the home page!

**Comment by tusharjain365** [comment]
Hi, I want to work on this issue if no one is working.
