### ISSUE TITLE
Reduce the loading time of resource page!

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#581]
### Feature description

Reduce the loading time of resource page!

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by ronitblenz** [comment]
I want to work on this issue

**Comment by SauravMukherjee44** [comment]
The loading time of the resource page is too high! Reduce it.

**Comment by ronitblenz** [comment]
Plz make it a medium issue, coz It is taking time to replace each and every embeds with the thumbnail links

**Comment by SauravMukherjee44** [comment]
Any update??

**Comment by ronitblenz** [comment]
I am sorry @SauravMukherjee44 My Exams are nearing.
I had to focus on that
I was on #2 in leaderboards..Still I had to quit
Its been 3 days I am not contributing
You can assign this issue to someone else. Thanks for investing time in me😇

**Comment by SauravMukherjee44** [comment]
No worries!

**Comment by Bijit-Mondal** [comment]
I wanna have this

**Comment by Srijita-Mandal** [comment]
Can I work on this issue under JWOC?

**Comment by sayan404** [comment]
I would love to work in this issue under JWOC.

**Comment by SauravMukherjee44** [comment]
@Srijita-Mandal Go for it!
