### ISSUE TITLE
Redesign Book Issue Section

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#582]
### Feature description

![Uploading image.png…]()

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by riiyaaa** [comment]
I would like to work on this issue under JWOC

**Comment by SauravMukherjee44** [comment]
Go for it!

**Comment by riiyaaa** [comment]
I will submit a pr request by tonight.
