### ISSUE TITLE
Feature: Add feature to sign in to actually work

### ISSUE THREAD

**Issue by Bijit-Mondal** [SauravMukherjee44/Aec-Library-Website#584]
### Feature description

I would like to work on that in firebase

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by SauravMukherjee44** [comment]
@Bijit-Mondal Go for it!

**Comment by SauravMukherjee44** [comment]
Yes, main branch only

**Comment by Bijit-Mondal** [comment]
I have create a PR
