### ISSUE TITLE
Feature: Build a high score storing system in the quiz section

### ISSUE THREAD

**Issue by soujo** [SauravMukherjee44/Aec-Library-Website#587]
### Feature description

Hi @SauravMukherjee44, I would like to implement a high score storing system using local storage in the quiz section.
If you like the idea then kindly assign the issue to me.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by SauravMukherjee44** [comment]
@soujo Go for it!
