### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by Aniket-508** [SauravMukherjee44/Aec-Library-Website#595]
### Reproduction steps
Check the website while scrolling down in mobile or desktop view giving bad UI/UX.

### Expected behavior

The speech to text icon and scroll to top should not overlap.

### Actual Behavior
![aec-library-wbsite netlify app_(Moto G4)](https://user-images.githubusercontent.com/71957423/153564030-46db098f-1a84-41ca-97ff-37629bbebfb2.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Aniket-508** [comment]
@SauravMukherjee44 I want to work on this under JWoC.

**Comment by SauravMukherjee44** [comment]
Go for it!
