### ISSUE TITLE
Feature: The courses and books links should open in the next window

### ISSUE THREAD

**Issue by sayan404** [SauravMukherjee44/Aec-Library-Website#610]
### Feature description

The courses and books links are opening within the window the user is in ... It is very disturbing to the user to browse the page at the very same time . 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by sayan404** [comment]
I want to work in this issue under JWOC .

**Comment by riiyaaa** [comment]
I would love to work on this issue under JWOC.
