### ISSUE TITLE
The Issue Book Section looks irregular with unequal margins and width of text field and heading and has "Category" placeholder missing.

### ISSUE THREAD

**Issue by Srishti2128** [SauravMukherjee44/Aec-Library-Website#622]
As can be seen from the below image these errors need to be resolved to improve the look and feel of the website.
<img width="433" alt="Screenshot 2022-02-27 134534" src="https://user-images.githubusercontent.com/90510806/155875430-6cea97f9-3589-4707-a307-4832d5bbd5c0.png">

**Comment by Srishti2128** [comment]
**I would like to take up this issue for GSSOC'22.**
I have tried to correct these issues in my local machine using the development console as can be seen in below image

<img width="430" alt="Screenshot 2022-02-27 142548" src="https://user-images.githubusercontent.com/90510806/155875590-8d9ab43b-397c-439f-8513-2d2312dcdc7e.png">

In addition, I have also made sure that the border radius of all input fields is same and consistent.

**Kindly assign me this issue** @SauravMukherjee44  so I can make final changes and make a pull request as soon as possible.

**Comment by SauravMukherjee44** [comment]
Go for it!

**Comment by Srishti2128** [comment]
> Go for it!

I have done the required changes and it is ready for the PR. But GSSOC'22 contribution period begins from March 1 so I will be sending a PR the first thing tomorrow morning.

**Comment by SauravMukherjee44** [comment]
Okay Cool!

**Comment by HarshKumarChoudary** [comment]
@Srishti2128, if you are not making PR, then @SauravMukherjee44 , please assign it to me.

**Comment by Srishti2128** [comment]
I have made the Pull Request #644 . Kindly merge it.
Thank You !!
