### ISSUE TITLE
Bug Report: at the footer the the subscribe to our news letter form don't have any padding margin around it: GSSOC Participant

### ISSUE THREAD

**Issue by AmolShelke2** [SauravMukherjee44/Aec-Library-Website#625]
### Feature description

Hey, Saurav I've found that at the AEC library website there is no padding and margin around the Subscribe to our newsletter form 
so I would like to make it look even nicer.
![aec-library-wbsite netlify app_index html](https://user-images.githubusercontent.com/95171638/155965420-131db241-2974-4feb-855e-ed238f968b23.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Khushi-Mattu** [comment]
Can you assign this to me under GSSOC'22?

**Comment by AmolShelke2** [comment]
If the issues are assigned to an person they only one who can work on that
you have to creat another issue.

**Comment by Abh1shekSingh** [comment]
Hello Sir @SauravMukherjee44  I can do this fix, Please assign this issue to me

**Comment by AmolShelke2** [comment]
Hey Abhishek this issue is assigned to me try to find another issues to
work with...

**Comment by Abh1shekSingh** [comment]
So keep working on it, i have right to ask the maintainer @AmolShelke2  .

**Comment by AmolShelke2** [comment]
yes, you have the right but you should have to find some issues on your own..

**Comment by AmolShelke2** [comment]
you first assign me this issue and then I created a pr you close and assign this to someone else!
