### ISSUE TITLE
Bug Report: User can add a book in issue section without specifying the author. 

### ISSUE THREAD

**Issue by AbhinavBattu** [SauravMukherjee44/Aec-Library-Website#626]
### Reproduction steps

Make select author field as mandatory in issue section and making "select author" option in dropdown unclickable

### Expected behavior

Select author should be mandatory field and if author is not in list then user should select "Others" option 

### Actual Behavior

![Screenshot (2)_LI](https://user-images.githubusercontent.com/92840673/156003992-b28ecc5f-47cf-4491-afc5-189953dcf777.jpg)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by AbhinavBattu** [comment]
Please assign me this issue. I would like to work on it.

**Comment by Aditya123987** [comment]
I want to work on this issue .

**Comment by Anshika-Srivastava** [comment]
There is already an option of 'other' in the website.

**Comment by AbhinavBattu** [comment]
The problem here is that the user can also issue a book by selecting "select author" option. In this case "select author" option should be only for reference this should unselectable option which doesn't get clicked.

**Comment by Anshika-Srivastava** [comment]
okay @AbhinavBattu you have been assigned this issue! You can start working. All the best.
