### ISSUE TITLE
Bug Report: CSS not linked in Sign Up page

### ISSUE THREAD

**Issue by AbhinavBattu** [SauravMukherjee44/Aec-Library-Website#627]
### Reproduction steps

By clicking Sign Up button on home page.

### Expected behavior

Clicking Sign Up button should show page with correct HTML and CSS

### Actual Behavior

![Screenshot (4)](https://user-images.githubusercontent.com/92840673/156007114-6267bc2f-7c0f-46f9-8cf9-0541b1ef87cb.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by AbhinavBattu** [comment]
Please assign me this issue. I would like to work on it.

**Comment by tanya-gupta25** [comment]
I want to work on this issue under GSSOC

**Comment by Aditya123987** [comment]
I want to work on this issue under GSSOC.

**Comment by 5kamakshi** [comment]
Please assign me this issue

**Comment by Anshika-Srivastava** [comment]
The sign-up page is already connected with css.
