### ISSUE TITLE
Bug Report: Web Developement Read More Button

### ISSUE THREAD

**Issue by Susmita-Dey** [SauravMukherjee44/Aec-Library-Website#632]
### Reproduction steps

When I clicked on the Read More button below the Web Development Section, it took me to a 404 error page.
![image](https://user-images.githubusercontent.com/79099734/156113030-8e141604-9a1c-4371-b38d-d6147d2a2aa8.png)

### Expected behavior

It should have taken me to the proper page without any error.

### Actual Behavior

**It actually showed me the following error page.**
![image](https://user-images.githubusercontent.com/79099734/156113150-3ab2b812-034c-4715-98e7-3f5cdf05bdf5.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Susmita-Dey** [comment]
I want this issue to be assigned to me. I'm a GSSOC'22 participant. I can work on this issue.

**Comment by devaaquib** [comment]
@Susmita-Dey  can u  define where you redirect the page so we check and if it appropriate we can assign you this issue.

**Comment by Susmita-Dey** [comment]
> @Susmita-Dey can u define where you redirect the page so we check and if it appropriate we can assign you this issue.

When I click on the READ MORE button it's redirecting me to an error page. But it should be redirected to a proper w3schools web development course page.

**Comment by Anshika-Srivastava** [comment]
@Susmita-Dey you have been assigned this issue. You can start working on it. All the best.

**Comment by Susmita-Dey** [comment]
> @Susmita-Dey you have been assigned this issue. You can start working on it. All the best.

Thanks for assigning it to me.
