### ISSUE TITLE
Bug Report: Book Donation Form Options

### ISSUE THREAD

**Issue by Susmita-Dey** [SauravMukherjee44/Aec-Library-Website#633]
### Reproduction steps

When I went to fill the **Book Donation Form**, there I found two mistakes in the dropdown menu.

### Expected behavior

It should be changed to State instead of Country and the last one from State to City.

### Actual Behavior

![image](https://user-images.githubusercontent.com/79099734/156114672-c042e7ea-69aa-48cd-b34d-775eefe8dc67.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Susmita-Dey** [comment]
I want this issue to be assigned to me. I'm a GSSOC'22 participant. I can work on this issue.

**Comment by SauravMukherjee44** [comment]
@Susmita-Dey Go for it!

**Comment by Susmita-Dey** [comment]
Thanks for assigning it to me.
