### ISSUE TITLE
Enhancing the UI of Contact Form and improving input fields

### ISSUE THREAD

**Issue by praveen-221** [SauravMukherjee44/Aec-Library-Website#634]
### Enhancing the UI of Contact Form and improving input fields

When I saw the contact form the fonts in the input field and textarea looks and contrasting. The textarea has no limit in minimizing and it hides the label.

The CSS also can be improved to look all the fields alike with using enough padding for labels and to make the form position appropriate.

![Screenshot (47)](https://user-images.githubusercontent.com/86505091/156123698-a7f14e26-adc4-4210-a81d-023632ce6f5b.png)

The form UI can be improved using CSS padding and transitions with matching colors and fonts. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by praveen-221** [comment]
I would like to work on this issue under GSSOC'22. Could you please assign me to this issue?

**Comment by Anshika-Srivastava** [comment]
@praveen-221 you have been assigned this issue. You can start working

**Comment by praveen-221** [comment]
Ok Thank you

**Comment by A1Kumari** [comment]
I would like to work on this issue under GSSOC
