### ISSUE TITLE
Improving UI of the footer including newsletter

### ISSUE THREAD

**Issue by Nanshi29** [SauravMukherjee44/Aec-Library-Website#638]
### Feature description

I m changing UI of the footer and make it more attractive. Also change the newsletter ui. Please assign this issue to me. Im a conributor at GSSoC'22.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Anshika-Srivastava** [comment]
Hey! You have been assigned this issue. All the best.
