### ISSUE TITLE
display message : "No search found"

### ISSUE THREAD

**Issue by ShlokMohanty** [SauravMukherjee44/Aec-Library-Website#64]
When we search for a book or an author then if the book is not there in our library then an error message "No search Found " should be displayed .

**Comment by ShlokMohanty** [comment]
![Screenshot (627)_LI](https://user-images.githubusercontent.com/59838234/135551366-237f4d6e-73a2-4753-bcc0-726f4ddf46f5.jpg)

**Comment by ggangix** [comment]
Hey, I can take this one, please assign to me. Thanks.
