### ISSUE TITLE
Documentation: Add PR Template

### ISSUE THREAD

**Issue by Pradumnasaraf** [SauravMukherjee44/Aec-Library-Website#641]
### Chnages 
- Adding a PR template
- Template path **`.github/PULL_REQUEST_TEMPLATE.md`**

### Template Preview (while creating a PR.)
![Screenshot from 2022-03-01 17-54-32](https://user-images.githubusercontent.com/51878265/156168840-66822d65-3e60-4026-8064-f967d66cf94b.png)

### Due to that, it we are also missing a check in Community Standards

![Screenshot from 2022-03-01 20-50-07](https://user-images.githubusercontent.com/51878265/156196619-52ae048d-6927-4367-809c-aa387f3de08d.png)

- **Contribution towards GSsoc`22, Thank you**

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Anshika-Srivastava** [comment]
@Pradumnasaraf you have been assigned this issue. You can start working
