### ISSUE TITLE
Documentation: Broken image links in README.md file on GitHub Mobile App

### ISSUE THREAD

**Issue by abhilipsasahoo03** [SauravMukherjee44/Aec-Library-Website#642]
### Description

# Issue Description

The Lines of Code shield image link is broken, while the Main Page screenshot and CodeIN Community banner links show broken on GitHub Mobile App. 

# Screenshot
![Screenshot_2022-03-01-21-50-24-379_com github android](https://user-images.githubusercontent.com/80174214/156207959-c4851c35-8871-4784-8c50-7f85a15a19c3.jpg)
![Screenshot_2022-03-01-21-50-34-511_com github android](https://user-images.githubusercontent.com/80174214/156207997-b8d5172c-8d48-4adb-bcd7-ebbf738018d2.jpg)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by abhilipsasahoo03** [comment]
> I'm GSSOC 22 contributor. If this issue is still available, please assign it to me. Also please add GSSOC22 label for that. Thanks

Hi @HarshKumarChoudary , actually the GSSOC'22 follows first-come rule so I'd be assigned the issue first, BUT if I fail to resolve it, I think you'd be free to take up this issue next! :)

**Comment by SauravMukherjee44** [comment]
@abhilipsasahoo03 Go for it!
