### ISSUE TITLE
Bug Report: No transitions in navigation bar.

### ISSUE THREAD

**Issue by Adhetya** [SauravMukherjee44/Aec-Library-Website#643]
### Reproduction steps

When you hover over certain elements of the website and navigation bar.

### Expected behavior

Transition should be smooth for better user experience.

### Actual Behavior

There are no transitions making the experience not very pleasant.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Adhetya** [comment]
I am a GSSOC 22 participant. I have identified this bug. So, can you assign this to me so I can start working on it?

**Comment by devaaquib** [comment]
@Adhetya  you can start working on it.
