### ISSUE TITLE
Bug Report: Spelling mistakes in quiz

### ISSUE THREAD

**Issue by aditiitomar** [SauravMukherjee44/Aec-Library-Website#646]
### Reproduction steps

**Spelling mistakes can be corrected simply.**

### Expected behavior

**Spellings should be correct.**

### Actual Behavior

![WrongQuizQues](https://user-images.githubusercontent.com/80448500/156214552-32e1588e-27c6-43f5-a3a1-1344dd22e715.png)

![WrongQuizQues3](https://user-images.githubusercontent.com/80448500/156215476-e25af134-82f0-4bf8-b6e2-8b3669d126af.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by aditiitomar** [comment]
Hey, @SauravMukherjee44 can you assign this issue to me?

**Comment by abhil2002** [comment]
Hey, Could you assign this issue to me, I am a GSSOC '22 contributor.

**Comment by devaaquib** [comment]
@abhil2002  @aditiitomar  try to contribute in code not in spelling mistakes like this.
