### ISSUE TITLE
Feature: To improve the Social Media Icons. 

### ISSUE THREAD

**Issue by Vivek-kumar21** [SauravMukherjee44/Aec-Library-Website#649]
### Feature description

![Screenshot from 2022-03-02 10-43-44](https://user-images.githubusercontent.com/92684075/156300051-d3dd2726-a3ce-4ef9-97be-8d16b9aec7d8.png)

I can improve the Social Media Icons and make them look even better.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by devaaquib** [comment]
@Vivek-kumar21 please deploy it bro.
