### ISSUE TITLE
Add Contributing Guidelines to the readme file

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#65]

**Comment by nshanbhag20001412** [comment]
Can you elaborate this issue?

**Comment by SauravMukherjee44** [comment]
You can add new elements to the readme page to make it attractive.

**Comment by arpanaditya** [comment]
What types of elements do you mean? Please explain it a bit more. May be give some examples. @SauravMukherjee44 then I can work on this issue. : )

**Comment by GowthamPB** [comment]
Hey can I work on this?

**Comment by anishsingh42** [comment]
Can elaborate the contributing guidelines section.
If yes please assign me this issue.

**Comment by SauravMukherjee44** [comment]
@arpanaditya Add Contributing guidelines to the readme section.

**Comment by arpanaditya** [comment]
@SauravMukherjee44 please assign this issue to me. I'll add contributing guidelines to the readme. Or else I'll create a separate page for it and link that to the readme : )

**Comment by Krishnapro** [comment]
Hello @SauravMukherjee44 I would like to work on this issue. I can add complete step about contribution guideline.

**Comment by arpanaditya** [comment]
Hey @SauravMukherjee44 , I have added contributing guidelines to the readme file as you have mentioned earlier. Do check this PR and merge this.
PR LInk: https://github.com/SauravMukherjee44/Aec-Library-Website/pull/135
You can close this issue now : )
