### ISSUE TITLE
Feature: To improve the Social Media Icons.

### ISSUE THREAD

**Issue by Vivek-kumar21** [SauravMukherjee44/Aec-Library-Website#650]
### Feature description

![WhatsApp Image 2022-03-02 at 10 56 27 AM](https://user-images.githubusercontent.com/92684075/156300798-c96c854f-0d80-469c-8ab9-e6b7f103e4ce.jpeg)

• I'm a GSSOC'22 Contributor and I'd like to make the appropriate change to this website.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Vivek-kumar21** [comment]
@SauravMukherjee44 Can you assign this to me so that I can work on it ASAP.

**Comment by 5kamakshi** [comment]
@SauravMukherjee44 Can you assign this to me I can do it.

**Comment by devaaquib** [comment]
@5kamakshi  yes you can start working on it.

**Comment by 5kamakshi** [comment]
yes I will do it

**Comment by 5kamakshi** [comment]
@devaaquib  Sir I completed my work Now what should I do can you Tell because I am new to Github

**Comment by devaaquib** [comment]
@5kamakshi  msg me on LinkedIn I will tell you on meet....? You can find my LinkedIn URL in my GitHub profile.
