### ISSUE TITLE
Feature: To improve newsletter form at end of page

### ISSUE THREAD

**Issue by prabhakar-dessai** [SauravMukherjee44/Aec-Library-Website#651]
### Feature description

The newsletter form at the end of the page has no proper css applied compared to other forms in the page. The input and subscribe button can be made to look better.
![feebackform](https://user-images.githubusercontent.com/61088215/156313555-ba64888a-6eed-45ec-8d17-b99f77c9a9f5.jpg)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by prabhakar-dessai** [comment]
Hey, i am a GSSoC '22 participant. Please assign this issue to me.
Proposal: 
Add better css overall, padding around  subscribe button and remove repetition of name in placeholder and before input
![newsletter](https://user-images.githubusercontent.com/61088215/156315037-68e4490e-0cff-4f10-b78f-8116c41d84b7.jpg)
.

**Comment by devaaquib** [comment]
@prabhakar-dessai you can start working on it.
