### ISSUE TITLE
Feature: No Navigate-To/Back-To Top Button : GSSoC22

### ISSUE THREAD

**Issue by gouravgupta02** [SauravMukherjee44/Aec-Library-Website#653]
### Feature description

Hi
While going through the resources page, I find out that there is **no Back-To Top button** in Resources page of the website. 

I feel it is a serious feature which needs to be implemented as soon as possible
I **want to work** on it and add a back to top button using my frontend skills under **GSSoC22** contribution.
![Screenshot (52)](https://user-images.githubusercontent.com/63440961/156317660-993796af-63d5-467f-a191-bb0ed7bbd5e7.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by gouravgupta02** [comment]
> @gouravgupta02 yes you can started working on it. All the best 😊

@devaaquib Thank you!😊

**Comment by pratiksrivastava01** [comment]
@gouravgupta02 What Should be the dimension of the back to top button in the website and the color combination of the box
