### ISSUE TITLE
Feature: improve play & pause button in Listen to Audiobooks 

### ISSUE THREAD

**Issue by iScreenager** [SauravMukherjee44/Aec-Library-Website#656]
### Feature description

sir, can you assign me this issue?

### 👀 Have you spent some time to check if this issue has been raised before?

- [ ] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [ ] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Navi68** [comment]
![aec](https://user-images.githubusercontent.com/87562957/156400231-c6d75cdf-a400-4a72-b225-986c9d43caf0.PNG)

I want to make the play button more attractive.

**Comment by devaaquib** [comment]
@Navi68 go for it.
