### ISSUE TITLE
To improve the buttons in the home page 

### ISSUE THREAD

**Issue by suhaillahmad** [SauravMukherjee44/Aec-Library-Website#657]
### Feature description

I have seen that the buttons on the home page in some sections are different and different in some section 

<img width="1440" alt="0F316F38-CBAC-4A6E-8BE1-6FE6F996D35F" src="https://user-images.githubusercontent.com/97229491/156377720-e9c10bd5-9c92-49f5-a467-01a1718e5252.png">
<img width="1440" alt="CDE5EF1F-A9A9-45D1-90B5-66605FD84616" src="https://user-images.githubusercontent.com/97229491/156377752-d1e7eeee-ecbc-4a6a-ab9a-70c9162e8f2c.png">
Please assign me this issue so i can work on it asap.
I am GSSOC contributor.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by devaaquib** [comment]
@suhaillahmad  you can start working on it.
