### ISSUE TITLE
 Feature: Improvement in the UI

### ISSUE THREAD

**Issue by Deep-anjali01** [SauravMukherjee44/Aec-Library-Website#659]
### Feature description

Can I change the font of the website and make it better than before. If you found it cool ,then add that otherwise not.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by devaaquib** [comment]
@Deep-anjali01 Yes you can start working on it. All the best.

**Comment by SauravMukherjee44** [comment]
@Deep-anjali01 Go for it!
