### ISSUE TITLE
Bug Report:  quick links not properly aligned in About page

### ISSUE THREAD

**Issue by puneetkaur2929** [SauravMukherjee44/Aec-Library-Website#661]
### Reproduction steps

![Screenshot (146)](https://user-images.githubusercontent.com/80326308/156384740-a4625b35-4ec4-4c27-8873-630518dedddd.png)

I want  to change the alignment of quick links so they are properly visible and serve their purpose

### Expected behavior

quick links will be aligned properly 

### Actual Behavior

the links are aligned in disorderly manner that  is not much attractive in look and moreover color is not matching with background.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by devaaquib** [comment]
@puneetkaur2929 You can start working on it. All the best.
