### ISSUE TITLE
The back button in the signup page doesn't work.

### ISSUE THREAD

**Issue by AbhinavBattu** [SauravMukherjee44/Aec-Library-Website#667]
### Reproduction steps

Go to the signup page .Then click the arrow button.

### Expected behavior

The button should have taken the user to the main page of the website.

### Actual Behavior

The button doesn't take the user to the main page due to wrong reference of the site.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by AbhinavBattu** [comment]
Please assign me this issue.

**Comment by devaaquib** [comment]
@AbhinavBattu Go for it.

**Comment by AbhinavBattu** [comment]
Will you assign it or i directly file a PR

**Comment by AbhinavBattu** [comment]
Can you please tell ,why did this issue wasn't merged.Was there any problem with it.
