### ISSUE TITLE
Improving ui of blog section of a website

### ISSUE THREAD

**Issue by KaranKulshrestha** [SauravMukherjee44/Aec-Library-Website#670]
convert this
![Capturae](https://user-images.githubusercontent.com/42493387/156424314-e220cd51-faa7-4751-b655-eec93716a674.PNG)
to this
![Capturea](https://user-images.githubusercontent.com/42493387/156424336-c0c61cb5-e6e0-41ce-a842-53ca56676ffb.PNG)

**Comment by KaranKulshrestha** [comment]
#669 I already push the code.

**Comment by VIDHI-BAJAJ** [comment]
I would  like to work on the assigment  can you assign me.

**Comment by KaranKulshrestha** [comment]
Please assign this issue to me I already pull the request #669

**Comment by devaaquib** [comment]
@KaranKulshrestha Go for it man!
