### ISSUE TITLE
Feature: Making the logo going to the main page

### ISSUE THREAD

**Issue by ZeyadTarekk** [SauravMukherjee44/Aec-Library-Website#671]
### Feature description

making the logo and "AEC LIBRARY" going to the main page of the website

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Mohit-1909** [comment]
@ZeyadTarekk Can you please tell me specifically whats the issue?

**Comment by ZeyadTarekk** [comment]
many pages the logo doesn't redirect to the main page
I can fix it 
I'm GSSoC participant

**Comment by devaaquib** [comment]
@ZeyadTarekk  You can start working on it.

**Comment by veerviren** [comment]
can I go for this issue @devaaquib ?

**Comment by ZeyadTarekk** [comment]
I'm working on it
