### ISSUE TITLE
Bug Report: Non working Link in a blog section

### ISSUE THREAD

**Issue by KaranKulshrestha** [SauravMukherjee44/Aec-Library-Website#675]
### Reproduction steps

This redirect show when we click on the web development post in the blog section.
![Captusre](https://user-images.githubusercontent.com/42493387/156446652-28796f56-50c7-4654-97d0-0bf145371873.PNG)

### Expected behavior

It should redirect to correct webpage.the 

### Actual Behavior

url is broken so I'll fix it.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by KaranKulshrestha** [comment]
I fix it #676

**Comment by alphaayu** [comment]
can you please assign this to me
