### ISSUE TITLE
Documentation: Adding CSS in sign-up page to make good UI

### ISSUE THREAD

**Issue by Rashmisingh-18** [SauravMukherjee44/Aec-Library-Website#681]
### Description

![blogs html - rashmi - Visual Studio Code 03-03-2022 11 27 54 AM](https://user-images.githubusercontent.com/90052358/156505544-70c69b34-993d-4987-b11c-abdb4e73935e.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by HarshKumarChoudary** [comment]
I want to contribute to it under GSSOC 22. Please assign it to me.

**Comment by ritikranjan12** [comment]
### @[Rashmisingh-18 I had corrected the signup page so that the CSS is working properly and made a Pull Request #688.
### It looks like this...
![Screenshot 2022-03-03 124058](https://user-images.githubusercontent.com/75849689/156566716-a823fbd6-51ca-4e37-a06f-de7d2b63efeb.png)

**Comment by devaaquib** [comment]
@Rashmisingh-18 Sorry! This issue is already resolved!
