### ISSUE TITLE
Improvement in about page footer ui

### ISSUE THREAD

**Issue by KaranKulshrestha** [SauravMukherjee44/Aec-Library-Website#694]
**Change This**
![Capture](https://user-images.githubusercontent.com/42493387/156613636-d3558e3c-9c6e-4322-b76a-e938145e8eb0.PNG)
**To This**
![Capturae](https://user-images.githubusercontent.com/42493387/156613764-a9aa996c-0997-4609-8b2c-948821b270f5.PNG)

**Comment by KaranKulshrestha** [comment]
Please assign me to improve it and merge my pull code under GSSOC 2022

**Comment by devaaquib** [comment]
@KaranKulshrestha Go for it man!
