### ISSUE TITLE
Bug Report: hover on speaker icon not working properly

### ISSUE THREAD

**Issue by ChetanDehane** [SauravMukherjee44/Aec-Library-Website#700]
### Reproduction steps

hover on a speaker icon in audio book under resources page is not working properly.
when we hover on speaker icon the volume bar stays there even if we don't hover on speaker icon.

### Expected behavior

the volume bar should visible only if we hover on speaker icon.

and there is lot off inconsistency in UI and functioning of a resources page.
i want to improve whole resources page.
please assign this task to me under GSSOC22 Chetan Dehane | Contributer

### Actual Behavior

![volume hover isseu](https://user-images.githubusercontent.com/62801180/156628422-19637ef2-d92c-401a-b2fe-8d1764b3cade.jpg)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by devaaquib** [comment]
@ChetanDehane  You can start working on it.
