### ISSUE TITLE
Bug Report: In the resources/ on footer, Top's quick link not at perfect position

### ISSUE THREAD

**Issue by MadhuSaini22** [SauravMukherjee44/Aec-Library-Website#704]
### Reproduction steps

When I go through the website, on resources down on footer the top button hides the copy right text. So, it should be shifted so that everything looks perfect.

### Expected behavior

It should be at its proper position may be  little bit down or upper.

### Actual Behavior

![2022-03-04_LI](https://user-images.githubusercontent.com/81684710/156707690-625fe98c-59f5-456b-8e66-03e70f90a504.jpg)
As you can see in the media, top button hides the footer content. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by MadhuSaini22** [comment]
hey @SauravMukherjee44 Could you assign this task to me as a GSSOc'22 label?

**Comment by devaaquib** [comment]
@MadhuSaini22 you can start working on it.

**Comment by Aishwarya123priya** [comment]
> 

Can I work on it? Assign this to me
