### ISSUE TITLE
Bug Report: Transition not occurring in Go to Top button of Home Page. Also no hover feature : GSSoC22

### ISSUE THREAD

**Issue by gouravgupta02** [SauravMukherjee44/Aec-Library-Website#710]
### Reproduction steps

Hi!
When I scrolled down the home page, the Back to Top button immediately appeared **without** any transition.
when I inspected what's wrong, I found a **bug**  in **CSS** part of this button.

Also, there is **no hovering effect** in this button, I would like to **add the hover effect** like color changing etc. under **GSSoC22** contribution.

### Expected behavior

The button should appear with the transition effects along with hover effects. 

### Actual Behavior

After scrolling, it actually popped out without any transition.

![Screenshot (55)](https://user-images.githubusercontent.com/63440961/156768911-6f882fa2-47fb-4b0f-9273-c814b6c846a2.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Anshika-Srivastava** [comment]
Hey @gouravgupta02 you have been assigned this issue. You can start working on this.
