### ISSUE TITLE
Bug Report: Contributors Page footer links are broken/not functional.

### ISSUE THREAD

**Issue by ramakrishna-mrk** [SauravMukherjee44/Aec-Library-Website#719]
### Reproduction steps

Link to Donate Books and Privacy Policy are broken in Footer section of Contributors Page.

Steps -
1. Linking 'Donate Books' to its working url.
2. And as of now there is no specific page for 'privacy policy', so temporarily linking it to index page until privacy policy is created.

GSSoC -22

### Expected behavior

Donate Books Page Should redirect to this page.
![Screenshot_44](https://user-images.githubusercontent.com/91669420/156872401-764a297d-f0d4-40ff-bbe6-8319920dc023.png)

### Actual Behavior

'Donate Books' page linked to broken url
![Screenshot_45](https://user-images.githubusercontent.com/91669420/156872433-726df324-b657-4279-87e0-7fbbf19b0368.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by ramakrishna-mrk** [comment]
I am a Contributor for GSSoC can you please assign this issue to me.

**Comment by SauravMukherjee44** [comment]
@ramakrishna-mrk Go for it!

**Comment by ramakrishna-mrk** [comment]
I have completed it and made the pull request
