### ISSUE TITLE
Add a Recommended Section of Book in the Index page

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#72]

**Comment by rajmunkhan** [comment]
I can create one Recommended Section of Book in the Index page, plz assign it to me.

**Comment by rajmunkhan** [comment]
hey @SauravMukherjee44 I have added recommended book section, kindly check out pull request #200 and let me know if you need any changes, thank you.

**Comment by rajmunkhan** [comment]
@SauravMukherjee44  I have updated the recommended book section beside the form and the page is still responsive #232 
![2021-10-04 (3)](https://user-images.githubusercontent.com/83774177/135884446-7b7b749d-3424-4598-853a-81acf878705d.png)

**Comment by vedant-shah** [comment]
Hey, I wanna try to work on this can u assign it to me ?

**Comment by SauravMukherjee44** [comment]
Do refer the above image
