### ISSUE TITLE
Bug Report: Newsletter validation 

### ISSUE THREAD

**Issue by soujo** [SauravMukherjee44/Aec-Library-Website#720]
The newsletter form in the footer section of the website has an incorrect validation. It alerts the user saying the form has been submitted if I only click on the submit button without even filling up the form.
I would like to correct the form validation and also implement a pop-up msg instead of a normal alert using javascript under JWOC.

**Comment by devaaquib** [comment]
@soujo You can start working on it.

**Comment by devaaquib** [comment]
@soujo its not under JWOC its under GSSOC'22

**Comment by soujo** [comment]
@SauravMukherjee44 Kindly look into it
