### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by Ishitacoding** [SauravMukherjee44/Aec-Library-Website#721]
### Reproduction steps

Bug in  Sign Up section .

### Expected behavior

Need of Css for amazing look and interface .

### Actual Behavior

![Screenshot (26)](https://user-images.githubusercontent.com/98388241/156873911-6b0dfcb1-f24f-45f8-b67a-b06346f62b73.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by devaaquib** [comment]
@Ishitacoding Sign-up section is fine. Check again.
