### ISSUE TITLE
Bug Report: Sing up page is not working properly

### ISSUE THREAD

**Issue by veerviren** [SauravMukherjee44/Aec-Library-Website#727]
### Reproduction steps

it seems like a normal page with no formatting and the blank page .

### Expected behavior

it should me proper match with website features ...

### Actual Behavior

this is what it looks like:-
![Screenshot (135)](https://user-images.githubusercontent.com/77713965/156887610-ec805d37-e861-4991-9bcf-e48e4cbd7c1f.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by veerviren** [comment]
can I go for this issue?

**Comment by devaaquib** [comment]
@veerviren  Bro check again it's working dude.
