### ISSUE TITLE
Feature: Adding Hover to footer button and adding extra things.

### ISSUE THREAD

**Issue by imaaquibali** [SauravMukherjee44/Aec-Library-Website#729]
### Feature description

Adding Hover on Footer button and adding links to all the options to make it more attractive.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by mariam199911** [comment]
I am a GSSOC 22 Participant please assign this issue to me

**Comment by purohitmansi** [comment]
Hello @devaaquib!

I am a GSSoC22 contributor. I would love to work on this issue and make PR as soon as I resolve the issue. Please do assign this to me.

ThankYou:)

**Comment by devaaquib** [comment]
@mariam199911 gor for it.

**Comment by mariam199911** [comment]
ok, thanks
