### ISSUE TITLE
Add Icons to the Navbar

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#73]

**Comment by rahulaarora** [comment]
Hey, I can do this 
plz assign
@SauravMukherjee44

**Comment by rohan26062001** [comment]
Hey, I would like to work on this issue

**Comment by SauravMukherjee44** [comment]
@rahulaarora Done!

**Comment by mifrasgaffoor** [comment]
Hey   @SauravMukherjee44  I would like to work on this issue

**Comment by Rathore-Devraj** [comment]
I would like to work on this issue

**Comment by rahulaarora** [comment]
> @rahulaarora Done!

@SauravMukherjee44 making pr soon

**Comment by rahulaarora** [comment]
@SauravMukherjee44 made the pr 
plz review

**Comment by yashsharma7128** [comment]
please assign this to me
