### ISSUE TITLE
in the quiz section , the codes for symbols like quotation , apostrophe are visible as it is.

### ISSUE THREAD

**Issue by itsAftabAlam** [SauravMukherjee44/Aec-Library-Website#732]
### Reproduction steps

this bug triggers when we access quiz section

### Expected behavior

the codes for symbols is visible as it is.

### Actual Behavior

instead the symbols should be visible and not there codes.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by itsAftabAlam** [comment]
please assign this to me

**Comment by devaaquib** [comment]
@itsAftabAlam Go for it man.

**Comment by AnshikaG0219** [comment]
Hey @itsAftabAlam Can you please assign this to me?

**Comment by itsAftabAlam** [comment]
@AnshikaG0219  I started working on this issue. You can check some other issue.
