### ISSUE TITLE
Bug Report: login button need margin and padding around it.

### ISSUE THREAD

**Issue by MadhuSaini22** [SauravMukherjee44/Aec-Library-Website#738]
### Reproduction steps

while going through I website, I found that Login button not looking perfect. It needs some styling as well as space around.

### Expected behavior

It should be at perfect position.

### Actual Behavior

![2022-03-07_LI](https://user-images.githubusercontent.com/81684710/156950605-a5c51065-5d2a-4bce-80c3-9e8239444a38.jpg)

Login button is almost colliding with the text down to it.
I'm a GSSOC'22 participant, assign this task to me with GSSOC'22 label

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Shobhit61730** [comment]
Can I fix this issue ?

**Comment by Anshika-Srivastava** [comment]
@MadhuSaini22 you have been assigned this issue. You can start working on the same.
