### ISSUE TITLE
Bug Report: Sign-Up form's Title and Button on it(Sign-in) needs some styling

### ISSUE THREAD

**Issue by MadhuSaini22** [SauravMukherjee44/Aec-Library-Website#739]
### Reproduction steps

While digging to the website, found that Signup page's form need title styling and it's button as well.

### Expected behavior

Title should be perfectly positioned to the component of SignUp.

### Actual Behavior

![2022-03-07 (1)_LI](https://user-images.githubusercontent.com/81684710/156951008-c1b81b21-aaff-4ef9-a287-c01400044512.jpg)
Title should be perfectly positioned and Sign-In button also need styling.
Please, assign this task to me with GSSOC'22 label

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Shobhit61730** [comment]
Can I fix this issue under Gssoc22 ?

**Comment by Anshika-Srivastava** [comment]
@MadhuSaini22 you have been assigned this issue. You can start working
