### ISSUE TITLE
Bug Report: Web Development Course section need more padding and margin

### ISSUE THREAD

**Issue by krithika2411** [SauravMukherjee44/Aec-Library-Website#744]
### Reproduction steps

while going through I website, I found that Web Development Course section not looking perfect. It needs some styling as well as space around.

### Expected behavior

It should not overlap over each other.

### Actual Behavior

![Screenshot (276)](https://user-images.githubusercontent.com/85842586/157039204-15236401-fbf3-49de-ab73-c52ddbf6c0c4.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by devaaquib** [comment]
@krithika2411 Go for it.

**Comment by devaaquib** [comment]
@krithika2411 someone is already working on it. Sorry!

**Comment by krithika2411** [comment]
@devaaquib no problem !
