### ISSUE TITLE
favicon missing in donate books page

### ISSUE THREAD

**Issue by rahulaarora** [SauravMukherjee44/Aec-Library-Website#75]
![image](https://user-images.githubusercontent.com/24794534/135660301-07f92538-85b5-45d2-94c8-bdcee11dff03.png)

**Comment by ahmadsohail404** [comment]
can i work on it?

**Comment by SauravMukherjee44** [comment]
@rahulaarora @ahmadsohail404 Who is gonna take this issue?

**Comment by SauravMukherjee44** [comment]
@ahmadsohail404 Cool!

**Comment by ahmadsohail404** [comment]
Done! Have a look @SauravMukherjee44
