### ISSUE TITLE
Bug Report: Image size is very small in About us page

### ISSUE THREAD

**Issue by Adhetya** [SauravMukherjee44/Aec-Library-Website#757]
### Reproduction steps

There is very little space between the image and terms and conditions text which doesn't make the UI look good. Also image size and social icons are very small and doesn't look clear.

### Expected behavior

UI should look clean with adequate spacing without wasting too much space

### Actual Behavior

<img width="1438" alt="Screenshot 2022-03-09 at 4 52 16 PM" src="https://user-images.githubusercontent.com/20537150/157432864-9a653d26-0ac6-49f0-9681-5f80ead3586a.png">

I would like to work on this issue. I am a GSSOC 22 participant.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by devaaquib** [comment]
@Adhetya  Start working on it.
