### ISSUE TITLE
Feature: Hover Effect Missing

### ISSUE THREAD

**Issue by Ishitacoding** [SauravMukherjee44/Aec-Library-Website#763]
### Feature description

I want to add hover effect in NCERT  Books section in Resources page  .

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)
![Screenshot (38)](https://user-images.githubusercontent.com/98388241/157608592-9069e23d-055c-43c1-a863-34447dfa1f34.png)

**Comment by SauravMukherjee44** [comment]
@Ishitacoding Go for it!
