### ISSUE TITLE
Feature: Add the missing Thumbnail

### ISSUE THREAD

**Issue by Princykri** [SauravMukherjee44/Aec-Library-Website#764]
### Feature description

In database Design and Development course section one Thumbnail is missing . 
![Screenshot (121)](https://user-images.githubusercontent.com/91013588/157603067-d4a4ac2e-3de2-4223-a196-d7685f9b96ec.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by SauravMukherjee44** [comment]
@Princykri Go for it!
