### ISSUE TITLE
Bug Report: FAQ link in HomePage Footer is not linked to FAQ section.

### ISSUE THREAD

**Issue by ramakrishna-mrk** [SauravMukherjee44/Aec-Library-Website#773]
### Reproduction steps

1. Creating a "Id" to FAQ Section.
2. And then linking FAQ  ahref to that Id.

### Expected behavior

![Screenshot_52](https://user-images.githubusercontent.com/91669420/158006860-6727bcf4-6995-48d8-9dd1-8dde6347e5b2.png)

### Actual Behavior

![Screenshot_51](https://user-images.githubusercontent.com/91669420/158006849-2d6cf0f2-c25b-444e-b34e-9527bd763b93.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by ramakrishna-mrk** [comment]
I am a Contributor for GSSoC can you please assign this issue to me.

**Comment by Anshika-Srivastava** [comment]
@ramakrishna-mrk you have been assigned this issue. You can start working.
