### ISSUE TITLE
Feature: Adding a reset button for book donation form

### ISSUE THREAD

**Issue by ankeeta-ahire** [SauravMukherjee44/Aec-Library-Website#775]
### Feature description

The reset button , if added, will clear all the previous data entered in the donation form so that a new entry can be made quickly.
I can do this, please assign me this issue.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Aman16-ai** [comment]
can i work on this issue ?

**Comment by Anshika-Srivastava** [comment]
@ankeeta-ahire you have been assigned this issue. You can start working.
