### ISSUE TITLE
Bug Report: Blog cards are not of equal size

### ISSUE THREAD

**Issue by Adhetya** [SauravMukherjee44/Aec-Library-Website#776]
### Reproduction steps

The size of cards in the blog section are not equal. There is also very little padding and gap between each of the cards.

### Expected behavior

Cards should be spaced out and have equal size

### Actual Behavior

Cards are unequal in size. With some styling, UI can be improved.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by MadhuSaini22** [comment]
Hey @SauravMukherjee44 , please assign this task to me under GSSOC'22 label.

**Comment by Anshika-Srivastava** [comment]
@Adhetya you have been assigned this issue. You can start working.

**Comment by Manushi05** [comment]
I would like to contribute to this issue as still padding is uneven and add more blogs other than technical.

**Comment by devaaquib** [comment]
@Manushi05  this issue is already solved. Please raise another issue.
