### ISSUE TITLE
 Feature: Regional language book section

### ISSUE THREAD

**Issue by Gyanvi908** [SauravMukherjee44/Aec-Library-Website#777]
### Feature description

we can have a regional language book section so that people from the different regions can access it. There we can put the books of the same type but in different languages. This made our website more convenient to the people and can become on-demand. Also if someone wants to read the same book in a different language he/she can access it easily without moving to the other website.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by devaaquib** [comment]
@Gyanvi908 Start working on it.
