### ISSUE TITLE
we can have a paid membership section for premium book  Feature: 

### ISSUE THREAD

**Issue by Anisharai10** [SauravMukherjee44/Aec-Library-Website#778]
### Feature description

In most of the library we always see two section one which is accessible to all and other one is for only for the person which have its premium membership . so we can add a section here so who so ever want to by membership can buy and read premium books.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by devaaquib** [comment]
@Anisharai10 Its Open-Source Project is free for everyone for a lifetime.

**Comment by Anisharai10** [comment]
Ok thanks for information

**Comment by Anisharai10** [comment]
Hello saurav i have raised new issue #782 please check and let me know if
it works.
