### ISSUE TITLE
we can have a book review section . Feature: 

### ISSUE THREAD

**Issue by Anisharai10** [SauravMukherjee44/Aec-Library-Website#782]
### Feature description

In the ace -library section we can add a book review section so that it can motivate lot of people to read book after the review

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by devaaquib** [comment]
@Anisharai10 Go for it.

**Comment by Anisharai10** [comment]
could you please tell me why the review section is not visible on the main
page. Because the issue was closed.

**Comment by Anisharai10** [comment]
hey saurav i am writing mail again and again because i need it . I want to
add this work on my resume and if  i am providing the link  my work
should be there please check what is the problem and fix it my review
section is not  visible on main page . i am attaching the screenshot of
page.
thanks regards
anisha rai
