### ISSUE TITLE
Feature: Code Optimization

### ISSUE THREAD

**Issue by Kumar-laxmi** [SauravMukherjee44/Aec-Library-Website#783]
### Feature description

In multiple files same JS and CSS code have been repeated again and again.

So Code Optimization could be done to increase readability and reduce complexity.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by devaaquib** [comment]
@Kumar-laxmi Start working on it.
