### ISSUE TITLE
Feature: storing books data in a JSON file

### ISSUE THREAD

**Issue by ahmed0saber** [SauravMukherjee44/Aec-Library-Website#792]
### Feature description

I can create a JSON file with the data of these books such as image url and download button url, then fetching this file with javascript to build the books section instead of copy then pasting the same div on each book added...
that will be the best solution sooner if someone wanted to create an API for adding books to the JSON file and getting data from it...

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by devaaquib** [comment]
@ahmed0saber Go for it.
