### ISSUE TITLE
Feature: improving SEO and adding an icon

### ISSUE THREAD

**Issue by ahmed0saber** [SauravMukherjee44/Aec-Library-Website#794]
### Feature description

I can add meta tags for better search engine optimization, correct alt attribute of images, add icon to the website, to make it SEO-Friendly..

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by devaaquib** [comment]
@ahmed0saber Start working on it.
