### ISSUE TITLE
Add animations to the website and make it responsive

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#8]

**Comment by rutuchandgude** [comment]
can I? @SauravMukherjee44

**Comment by rutuchandgude** [comment]
Can I try this #8 issue? @SauravMukherjee44

**Comment by SauravMukherjee44** [comment]
Yeah Sure! I have assigned the issue to you.

**Comment by SauravMukherjee44** [comment]
First fork the project, so that I can assign it.

**Comment by SauravMukherjee44** [comment]
Subscribe to that issue #8

**Comment by rutuchandgude** [comment]
@SauravMukherjee44  I have animated  it, if you like please merge it.

**Comment by rutuchandgude** [comment]
@SauravMukherjee44  I have animated  it, if you like please merge it.
