### ISSUE TITLE
Create a About Section of the Library Website

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#80]

**Comment by RahulSharma4329** [comment]
Hey I would like to work on this issue can you please assign this issue to me.

**Comment by yogendra-17** [comment]
hey, I would like to work on this issue, can you please assign it to me.?

**Comment by Amritanshu02** [comment]
Hello, I would like to work upon this issue, please assign me to it

**Comment by yadavashishdhirendra** [comment]
Hey @SauravMukherjee44 I would like to work on this section can u assign it to me!
