### ISSUE TITLE
Feature: Toggle the visibility (show/hidden) of password while signing up.

### ISSUE THREAD

**Issue by Siddhesh777** [SauravMukherjee44/Aec-Library-Website#802]
### Feature description

It is necessary to have a button which toggles the visibility of password from show to hide and vice-versa.
We can implement this using react useState hook.

![1](https://user-images.githubusercontent.com/77476772/159226387-9f3cf421-db3b-4c12-aaea-42435ac93d89.png)

I am contributor at gssoc'22.
Please assign this issue to me.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by devaaquib** [comment]
@Siddhesh777 Start working on it.
