### ISSUE TITLE
Feature: Changes in Login Page image

### ISSUE THREAD

**Issue by IshitaSharma26** [SauravMukherjee44/Aec-Library-Website#805]
### Feature description

![Screenshot (48)](https://user-images.githubusercontent.com/98388241/159446522-4df61de5-5ace-44b9-88f6-3260af88dcc6.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by SauravMukherjee44** [comment]
@IshitaSharma26 Go for it!

**Comment by Sukriti-m** [comment]
Hi @SauravMukherjee44 
If this task is being delayed, then I'd be glad to work on this issue.
I'd be grateful if you could assign this task to me under GSSoC'22.
