### ISSUE TITLE
Bug Report: Navigation tab for NCERT books and Audio books in Resources page

### ISSUE THREAD

**Issue by Riddhi9570** [SauravMukherjee44/Aec-Library-Website#809]
### Reproduction steps

In resources page, the navigation tab for "NCERT Books" and "Audio Books" is not given. And the "Home" and the "About"  tabs are mixed with the resources list.

### Expected behavior

The "NCERT Books" and "Audio Books" should be added in the quick navigation tab, and "Home" button should be present at different location.

### Actual Behavior

![Screenshot (23)](https://user-images.githubusercontent.com/72887868/159807744-73ec2634-cafb-4f03-9e21-3f7c4952f9ad.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by SDE-ADNAN** [comment]
Pls assign me to do it 
"will add a home icon at the start of the section and add NCERT books and Audio Books button"

**Comment by Anshika-Srivastava** [comment]
@Riddhi9570 you have been assigned this issue. You can start working!

**Comment by SDE-ADNAN** [comment]
great starting ASAP

**Comment by Riddhi9570** [comment]
@SDE-ADNAN I think you are having a confusion. This issue has not been assigned to you, it's assigned to me. You may create a different issue and get yourself assigned. Best of luck!

**Comment by SDE-ADNAN** [comment]
ok mybad i have a issue ready will raise it very soon happy coding
