### ISSUE TITLE
Add Contact Us details at the Footer

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#81]

**Comment by RahulSharma4329** [comment]
I would like to work on this issue can you please assign this to me

**Comment by mifrasgaffoor** [comment]
Hey @RahulSharma4329 i am searching for projects and issues for my very first hacktoberfest contributions .... can you please assign it to me .
Thanks in advance!

**Comment by yogendra-17** [comment]
hey!I would love to work on this issue, can you please assign it to me

**Comment by ayasahmad63** [comment]
I also love to work on it.

**Comment by SauravMukherjee44** [comment]
Whoever wants to work, Create a PR for the Same.

**Comment by yashsharma7128** [comment]
please assign this to me
