### ISSUE TITLE
Bug Report: Scroll Bar at landing page is not working.

### ISSUE THREAD

**Issue by Priyanshi136** [SauravMukherjee44/Aec-Library-Website#819]
### Reproduction steps

As we click on the link to the website,  the landing opened has scroll bar but it isn't working, on the mouse click.

### Expected behavior

It actually have to scrolls down and shows the whole content, after clicking thorugh the mouse

### Actual Behavior

But isn't showing it. Only working when clicked from the keyboard.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by SauravMukherjee44** [comment]
@Priyanshi136 Go for it!

**Comment by Priyanshi136** [comment]
okay, i will try to raise PR as soon as i can.

**Comment by Priyanshi136** [comment]
hey, i want to ask one thing like i had did changes what i think are needed, now i want to check if they are giving required result or not. So how can i check it?
