### ISSUE TITLE
Redesign the Home Page 

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#82]

**Comment by yashpatel458** [comment]
I am on it! Can you please assign this task to me?

**Comment by ahmadsohail404** [comment]
I can go ahead wid it

**Comment by aswinikalyan30** [comment]
I can work on it too!

**Comment by SauravMukherjee44** [comment]
@aswinikalyan30 Go for it !

**Comment by yashsharma7128** [comment]
please assign this to me

**Comment by aswinikalyan30** [comment]
> @aswinikalyan30 Go for it !

Hey, you can assign it to someone else! I am working on a few other ones, because of which I won't be able to move forward with this

**Comment by Sin-Sumit** [comment]
@SauravMukherjee44 please add description means what to redesign in home page.

**Comment by sowmiya-venkatesan** [comment]
I would like to contribute here, please do add proper description on what to redesign

**Comment by SauravMukherjee44** [comment]
Create a PR.

**Comment by aniket1104** [comment]
i can style the dropdown menus and css of the page to make it look better....i would like to work on this issue.
previously i worked on the styling of this project. https://namankhare.github.io/yet-another-tip-calculator/
