### ISSUE TITLE
Bug Report: Some Books in Recommended Book Section not working Properly

### ISSUE THREAD

**Issue by Jyoti6828** [SauravMukherjee44/Aec-Library-Website#820]
### In the recommended book section -
![image](https://user-images.githubusercontent.com/78480983/161210161-ad6b37cb-7ec7-4491-ba88-5f0136920837.png)

### The books
![image](https://user-images.githubusercontent.com/78480983/161210314-c61b927c-5aaf-42a6-98c9-073ec3b47663.png)
![image](https://user-images.githubusercontent.com/78480983/161210388-a644033e-ccc0-49a6-a890-d188e6a9062c.png)

#### It should open the PDF version after clicking on Download as pdf 
![image](https://user-images.githubusercontent.com/78480983/161210752-e112769d-7f2d-4c64-8a66-559a232fffb2.png)

#### It actually looks like 
![image](https://user-images.githubusercontent.com/78480983/161210852-cc81c29c-b53c-4b71-8f22-a163848d2cd3.png)
![image](https://user-images.githubusercontent.com/78480983/161210891-f26270d8-28e8-4a19-8029-7625c662d916.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Jyoti6828** [comment]
I want to work on this issue under GSSoC'22.

**Comment by SauravMukherjee44** [comment]
@Jyoti6828 Go for it!

**Comment by Rishita489** [comment]
Hey @SauravMukherjee44 , I am a GSSOC'22 Contributor . Can  you please assign this issue to me . I have send the PR solving the above issue . You can review and merge it .
