### ISSUE TITLE
Fix the extra space and center the all sections 

### ISSUE THREAD

**Issue by codingkush** [SauravMukherjee44/Aec-Library-Website#830]
### Reproduction steps

 I visited this website and i scrolled horizontally then i found the extra space in left side of whole website and the ' your books'  and ' choose and read books ' section are not center...

![Screenshot_20220405-192336~2](https://user-images.githubusercontent.com/78756312/161770366-657f703e-1e2c-4e2d-9a9d-65d53270bdf3.png)

### Expected behavior

There should not extra space and the ' your books'  and ' choose and read books ' section should be  center...

### Actual Behavior

But when you scroll horizontally ,you find extra space left side of website....and the ' your books'  and ' choose and read books ' section are not center...

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Sukriti-m** [comment]
Hi @codingkush 
I'd be glad to work on this issue.
I'd be grateful if you could assign this task to me under GSSoC'22.

**Comment by codingkush** [comment]
@Sukriti-m  I'm also a GSsoc 22 contributer and I also want to work on this issue

**Comment by codingkush** [comment]
Plz ... assign this issue to me under GSsoc 22

**Comment by SauravMukherjee44** [comment]
@codingkush Align the element at the center in the mobile view.

**Comment by codingkush** [comment]
ok...i do
