### ISSUE TITLE
Bug Report: Redesign signup page

### ISSUE THREAD

**Issue by Adhetya** [SauravMukherjee44/Aec-Library-Website#834]
### Reproduction steps

The background image looks good, but is not related to the website theme. Also, it would be better if the form is aligned in the center. Also, in mobile view, there is overlap between text and sign-in button. 
<img width="1440" alt="Screenshot 2022-04-08 at 8 10 43 AM" src="https://user-images.githubusercontent.com/20537150/162352754-397b0486-ab65-473f-864a-78e348a80bcb.png">

### Expected behavior

Form should be centered and background image should be related to library website.  Also, there should not be any overlap between sign up button and text.

### Actual Behavior

There is overlap and form is not centered

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Anshika-Srivastava** [comment]
You can start working on the issue.
