### ISSUE TITLE
Navbar items not aligned properly in center in Resources Page

### ISSUE THREAD

**Issue by ahmadsohail404** [SauravMukherjee44/Aec-Library-Website#84]
<img width="1440" alt="Screenshot 2021-10-02 at 3 53 29 AM" src="https://user-images.githubusercontent.com/72069769/135692244-2077eab6-1666-47c4-aa3d-b6ee64e99c35.png">

**Comment by ahmadsohail404** [comment]
Assign me this please

**Comment by copyNinja1219** [comment]
@SauravMukherjee44  I just made the navbar responsive please check : ) #98
