### ISSUE TITLE
Minor changes to readme

### ISSUE THREAD

**Issue by Akshata-Gunapache** [SauravMukherjee44/Aec-Library-Website#846]
### Description

The "open in vscode" option is not visible as an svg batch.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Akshata-Gunapache** [comment]
I am a GSSoC 2022 participant . Please assign this issue to me. I would like to make the above change and other necessary changes to the readme.

**Comment by devaaquib** [comment]
@Akshata-Gunapache can you specify your changes.

**Comment by Akshata-Gunapache** [comment]
![IMG_20220512_113637](https://user-images.githubusercontent.com/96786500/168003069-f72cae84-b585-4428-8d27-74960de67bb9.jpg)
