### ISSUE TITLE
Exchange the dummy books with NCERT books in NCERT page 

### ISSUE THREAD

**Issue by Riddhi9570** [SauravMukherjee44/Aec-Library-Website#850]
### Feature description

Exchange the dummy books in NCERT page with the real NCERT books. I will add over 65 NCERT books of classes 8,9,10,11,12.

![Screenshot (84)](https://user-images.githubusercontent.com/72887868/166147267-2df213ce-f69b-4854-819d-83af9f760e15.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by devaaquib** [comment]
@Riddhi9570 go for it!

**Comment by rohitkhicher001** [comment]
I would like to work on it as a GSSOC'22 participant.

**Comment by dpmohod14** [comment]
I would like to work on it

**Comment by Shivyoddha** [comment]
Hi @Riddhi9570 ,
I would like to  work on this issue, could you please assign it to me?

**Comment by Shivyoddha** [comment]
Hi @imaaquibali ,
I would like to work on this issue could you please assign it to me?

**Comment by Panda-Abhisek** [comment]
Hi @SauravMukherjee44 
I wanna work on this.
Please assign this to me.

**Comment by ABbansal235** [comment]
Could you please assign this task to me?

**Comment by arshbhatia8** [comment]
I would like to work on it.

**Comment by SauravMukherjee44** [comment]
@Panda-Abhisek Go for it!

**Comment by tmsagarofficial** [comment]
@SauravMukherjee44 pls assign this issue to me ... I would love to give it a try an complete

**Comment by Panda-Abhisek** [comment]
@SauravMukherjee44 Ok! ✌

**Comment by Panda-Abhisek** [comment]
@Riddhi9570  @SauravMukherjee44 - issue #850
1. first of all, I will make PR of adding all the book images to the Image folder.

**Comment by Panda-Abhisek** [comment]
Hey @SauravMukherjee44, I made a PR in which I have added all the required NCERT book cover pages in jpg format.
Please check and merge them. So that I can move further.
After this, I will be adding the links to the pdf, chapters of different subjects of different classes. one by one
