### ISSUE TITLE
Improving CSS for the issue here, your books and choose books sections Gssoc 2022

### ISSUE THREAD

**Issue by prabhakar-dessai** [SauravMukherjee44/Aec-Library-Website#857]
### Feature description

The sections on front page have different style, some are highlighted and some don't have proper padding. I would like to adjust the CSS for the sections so they fit the website better and are uniform in design.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by prabhakar-dessai** [comment]
I'm a Gssoc 2022 participant, please assign this issue to me.

**Comment by the-illuminatus** [comment]
can i work on this issue under gssoc22?

**Comment by ayesha-fir** [comment]
> I'm a Gssoc 2022 participant, please assign this issue to me.

hello,I want to contribute to open source and I am new comer can you help me
