### ISSUE TITLE
Add recommended books and Resources section on the Blank right side

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#86]

**Comment by copyNinja1219** [comment]
![lib1](https://user-images.githubusercontent.com/72335379/135703351-a1995bbb-4575-49a6-946a-c30b887e5f1a.png)


please specifiy where it must be added 1 or 2 or any other location ?

**Comment by SauravMukherjee44** [comment]
![rr](https://user-images.githubusercontent.com/72380920/135703463-beafaf87-5125-419a-86f9-547d335c04f8.PNG)

**Comment by SauravMukherjee44** [comment]
Add a Section over there, Feature content over there.
