### ISSUE TITLE
Update YouTube Link in the footer

### ISSUE THREAD

**Issue by Siddhi-Mundada** [SauravMukherjee44/Aec-Library-Website#864]
### Feature description

I would like to add Youtube link in the footer.
Please assign this issue to me under gssoc'22.
Thanks!

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by AmanGit010** [comment]
Is this issue still open ?

**Comment by dpmohod14** [comment]
hello,
I would like to add Youtube link in the footer.
Please assign this issue to me
