### ISSUE TITLE
Bug Report: Web Development Course image is not linked to its updated Image

### ISSUE THREAD

**Issue by Shivyoddha** [SauravMukherjee44/Aec-Library-Website#873]
<b>ISSUE</b>

When we open the Resources section and see the Web Development courses Section we notice that image for one of the courses is not present.

### Expected behavior

<b>It should show the the image of the course in it.</b>

### Actual Behavior

This is the Screenshot of the improperly linked  image.
![image](https://user-images.githubusercontent.com/97729353/193232563-3af5c108-d7d2-4211-97e5-ec62543f0adf.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Shivyoddha** [comment]
Hi @imaaquibali ,
Could u assign this issue to me as a part of Hacktoberfest?

**Comment by SauravMukherjee44** [comment]
@Shivyoddha Go for it!
