### ISSUE TITLE
Bug Report : "Read More" Button in blog pagenot properly placed.

### ISSUE THREAD

**Issue by imyoungsparda** [SauravMukherjee44/Aec-Library-Website#876]
### Reproduction steps

![image](https://user-images.githubusercontent.com/112796825/193380085-a472469c-7d45-4270-829d-7b58a384ea75.png)

Read More button appears outside of the card body in some of the cards in Blog Page.

### Expected behavior

Read More button should be inside the card in all the cards in blog page.

### Actual Behavior

Read more button must be inside the card.

![image](https://user-images.githubusercontent.com/112796825/193381216-13306818-5473-4b9d-938a-c4e64beab3cf.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by imyoungsparda** [comment]
Could you please assign this task to me?

**Comment by SauravMukherjee44** [comment]
@imyoungsparda Go for it!

**Comment by ABbansal235** [comment]
Could you please assign this task to me?
