### ISSUE TITLE
Minor changes to the Book Donation Form

### ISSUE THREAD

**Issue by tushar54594** [SauravMukherjee44/Aec-Library-Website#877]
Description
In the "Select State" input area, It should be mentioned that "Please select Country first" but it is mentioned "Please select State first"
Similarly In the "Select City" input area, It should be mentioned that "Please select State first" but it is mentioned "Please select City first". 

👀 Have you spent some time to check if this issue has been raised before?
 I checked and didn't find similar issue

🏢 Have you read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)?
 I have read the Code of Conduct

![Screenshot (500)](https://user-images.githubusercontent.com/94536522/193394954-3e498f27-03b8-4568-87f7-e663223d8408.png)

@SauravMukherjee44 Please assign me this issue. I will be contributing this for hacktoberfest.

**Comment by rahulaarora** [comment]
Hi, I can fix this, can you assign this to me?

**Comment by tushar54594** [comment]
@rahulaarora I only opened this issue. So I guess you should check for any other issues or create your own issue.

**Comment by SauravMukherjee44** [comment]
@tushar54594 Go for it!

**Comment by moksh2212** [comment]
hello I can fix this error. Please assign to me.

**Comment by tushar54594** [comment]
@moksh2212 I already did it and submitted the PR. You can look for any other issues.
