### ISSUE TITLE
Bug Report: Fix Browser Console Errors 

### ISSUE THREAD

**Issue by rahulaarora** [SauravMukherjee44/Aec-Library-Website#878]
### Reproduction steps

When you open the website in the browser and open the browser console, you see errors and some script values

### Expected behavior

Browser console should be clear 

### Actual Behavior

![image](https://user-images.githubusercontent.com/24794534/193398739-5723600b-77e0-4b10-a1cb-7b0a09281bd7.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by rahulaarora** [comment]
Hi  @imaaquibali @SauravMukherjee44 , could you please assign this issue to me as a part of hacktoberfest?

**Comment by SauravMukherjee44** [comment]
@rahulaarora Go for it!

**Comment by rahulaarora** [comment]
@SauravMukherjee44 Review this PR, I have fixed all errors
