### ISSUE TITLE
Bug Report: Choose and read books section right shifts in mobile view 

### ISSUE THREAD

**Issue by rahulaarora** [SauravMukherjee44/Aec-Library-Website#879]
### Reproduction steps

When I opened the website in mobile, the choose and read books section is out of place because of the wrong margin 

### Expected behavior

It should be in between the placeholder

### Actual Behavior

![image](https://user-images.githubusercontent.com/24794534/193399417-2540ea19-60b5-4e81-a7e1-ba9812ab2dc9.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by rahulaarora** [comment]
Hi @imaaquibali @SauravMukherjee44, could you please assign this issue to me?

**Comment by SauravMukherjee44** [comment]
@rahulaarora Go for it!
