### ISSUE TITLE
Feature: I would like to improve the UI of the Blogs page.

### ISSUE THREAD

**Issue by JenilGajjar20** [SauravMukherjee44/Aec-Library-Website#886]
### Feature description

The current UI of the Blogs page is not looking attractive. I would like to change the design. 

![BlogsPageUI](https://user-images.githubusercontent.com/68738624/193410317-c4085d37-d448-4cd7-937e-55594745eccf.jpg)
 
**@SauravMukherjee44** Can you please assign me this task as a part of Hactoberfest?

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by SauravMukherjee44** [comment]
@JenilGajjar20 Go for it!

**Comment by champati-v** [comment]
Hi! @SauravMukherjee44 , It seems like the above issue has not been addressed since a long time. Can you assign me the same.
Thanks

**Comment by anjaliSilawat** [comment]
I would like to work on this issue , please assign it to me

**Comment by SauravMukherjee44** [comment]
@anjaliSilawat Go for it!
