### ISSUE TITLE
Feature: Enhancing Footer section of About page 

### ISSUE THREAD

**Issue by iamrahul8** [SauravMukherjee44/Aec-Library-Website#888]
### Feature description

Footer section of About page should be enhanced 
- text are not visible properly

![SAYlL1664650047](https://user-images.githubusercontent.com/72541381/193421992-a40d0f14-7bfc-4238-9da5-ec79d1ff627c.jpg)
---
Please assign this issue to me , I want to contribute under ```hacktoberfest```

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by SauravMukherjee44** [comment]
@iamrahul8 Go for it!
