### ISSUE TITLE
Enhancing Footer Section of Resources Page.

### ISSUE THREAD

**Issue by Mahak008** [SauravMukherjee44/Aec-Library-Website#894]
### Reproduction steps

Contact Us and Social Media Icons are not aligned properly.

### Expected behavior

Centralize the contact us and social media icons or shorten the about us, general message and feedback section and made a 4th column of contact us section.

### Actual Behavior

Contact us and Social Icons are not giving a good look to the footer.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by SauravMukherjee44** [comment]
@Mahak008 Go for it!

**Comment by cmaguluri1305** [comment]
I want to contribute can anyone assign the issue to me?

**Comment by anjaliSilawat** [comment]
I would like to work on this issue , please assign it to me
