### ISSUE TITLE
Bug Report: Change the YouTube links in footer of all pages of the website

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#896]
### Reproduction steps

Add this New YouTube Link:  https://bit.ly/CodeINYouTube

### Expected behavior

Change the old link

### Actual Behavior

...

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by RahulSankhla312** [comment]
hey @SauravMukherjee44 can you assign this issue to me.

**Comment by Asmit2952** [comment]
I can work on this

**Comment by Dhanshriborse** [comment]
hey can you please assign this to me

**Comment by Baivab007** [comment]
i can work on this plase assign it to me.

**Comment by toukirkhan** [comment]
assign this to me

**Comment by Devashish08** [comment]
hey there this is my first time can you assign this to me i am new to open source thanks.

**Comment by AsmaKacem1** [comment]
Hi @SauravMukherjee44 ,
can i work on this issue?

**Comment by Sumedh-byte** [comment]
Hello @SauravMukherjee44 , I am a web developer with experience of 2 internships. I am interested in resolving this issue. Can you please assign it to me?

**Comment by bhavya-sharma26** [comment]
Hi @SauravMukherjee44 can u assign this task to me ? I will be able to complete it in time with proficiency , versatility and clarity

**Comment by SahilSingh177** [comment]
Assign this issue to me.

**Comment by AK-shat-JAIN** [comment]
Hello @SauravMukherjee44  I want to resolve this task you can assign it to me

**Comment by SauravMukherjee44** [comment]
@Dhanshriborse Go for it!
