### ISSUE TITLE
Feature: Update the Navigation Bar in ncert.html page

### ISSUE THREAD

**Issue by smilewithkhushi** [SauravMukherjee44/Aec-Library-Website#901]
### Feature description

I want to add a proper navigation bar in ncert.html page which has links to the following
- home page
-  resources page
- a new section for CBSE Board Exams PYQ's
- a new section for CBSE board Exams sample papers 
- changing the heading from "NCERT BOOKS" to NCERT BOOKS & OTHER RESOURCES

<img width="960" alt="Screenshot (892)" src="https://user-images.githubusercontent.com/102166679/193448769-39cf9bbc-0833-42d9-bee1-7c66d777934f.png">

Please approve and assign this issue : )

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by arsh-111** [comment]
Hey can u assign me this issue?
