### ISSUE TITLE
Feature:   Linking the new page cbse_notes.html with resource.html

### ISSUE THREAD

**Issue by smilewithkhushi** [SauravMukherjee44/Aec-Library-Website#903]
### Feature description

Linking the new page cbse_notes.html with resource.html. cbse_notes.html will be a new page created for displaying the cbse notes for all subjects (class 11th and 12th). (feature issue has been requested before)

This issue is regarding the following features : 

- Need to link the new page (cbse_notes.html) to the navbar of resource.html  
- Also, Need to fix this image using web development courses section. 

<img width="945" alt="Screenshot (894)" src="https://user-images.githubusercontent.com/102166679/193449277-b8166ff9-9a03-41a6-97c9-a526fa76aa2f.png">

- Few notes/documents from cbse_notes.html can be included in the body of resource.html, i.e, below the section contents of 
NCERT BOOKS. 

<img width="960" alt="Screenshot (896)" src="https://user-images.githubusercontent.com/102166679/193449497-43077576-ee06-412b-9da2-aac5bce6b648.png">

Please approve and assign this issue to me if you find it relevant : )

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by Esha-01** [comment]
Hey,@smilewithkhushi can you assign this to me.I can work on this.

**Comment by Shivyoddha** [comment]
Hi @smilewithkhushi ,
The web development image is properly working. The screenshot of the same is below-

![image](https://user-images.githubusercontent.com/97729353/193459751-f80d6c02-656b-42c8-ad1b-235e7e69de9a.png)
