### ISSUE TITLE
Bug Report: Improper alignment and styling of choose and read book form.

### ISSUE THREAD

**Issue by toukirkhan** [SauravMukherjee44/Aec-Library-Website#908]
### Reproduction steps

- As soon as you get into the landing page of the website of AEC Library. Just check the "choose and read book" section. 
- It is clearly visible that the "choose and read book" section or box is not aligned perfectly with its upper neighbour "Your Books".

### Expected behavior

The element should be aligned in this manner and it should look like this.
![Screenshot 2022-10-02 173335](https://user-images.githubusercontent.com/88899011/193453003-d75f9f3c-e713-42fc-b69e-29a958319441.png)

### Actual Behavior

But it is actually behaving like this which looks a bit awkward.
![Screenshot 2022-10-02 172343](https://user-images.githubusercontent.com/88899011/193453039-9b88f385-e3c4-412f-b7b6-ef48f9abee58.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by toukirkhan** [comment]
Please assign me this issue under hacktoberfest label. Thank you.

**Comment by SauravMukherjee44** [comment]
Go for it!

**Comment by toukirkhan** [comment]
Thnaks!!
