### ISSUE TITLE
Bug Report: Login Form

### ISSUE THREAD

**Issue by Sumedh-byte** [SauravMukherjee44/Aec-Library-Website#911]
### Reproduction steps

I found a bug on Login Page.

### Expected behavior

The side image of login form must be related to website content.

### Actual Behavior

Actually the side image has to be appropriate to the website.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by SauravMukherjee44** [comment]
Go for it!

**Comment by Sumedh-byte** [comment]
Than you for assigning it to me. I will update you soon.
