### ISSUE TITLE
Feature: Adding more states for Countries like Australia and Canada in the Book Donation Form

### ISSUE THREAD

**Issue by AishwaryaParab** [SauravMukherjee44/Aec-Library-Website#912]
### Feature description

Adding in more states for both the countries. I want to populate the data so that people from these states can also contribute using the donation form.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by AishwaryaParab** [comment]
@SauravMukherjee44 could you please assign this issue to me?

**Comment by SauravMukherjee44** [comment]
Go for it! Add Indian Cities.

**Comment by RishitaGangwal** [comment]
Hey, please assign this issue to me!

**Comment by HARSHSUHANE17** [comment]
> Go for it! Add Indian Cities.

I have some cities . Please check and merge it (PR#922)

**Comment by RishitaGangwal** [comment]
I have added cities under Madhya Pradesh State. Please check and merge my request (PR #926 ) @SauravMukherjee44 

Thanks!

**Comment by HARSHSUHANE17** [comment]
HEY @RishitaGangwal are you also a newbie to open source?

**Comment by preetu391** [comment]
Hey, please assign this issue to me!

**Comment by amisha123prajapati** [comment]
Hello @SauravMukherjee44 , I would like to contribute to it. Could you please assign this issue to me!
