### ISSUE TITLE
Feature: I would like to enhance the UI of the Resources page.

### ISSUE THREAD

**Issue by AishwaryaParab** [SauravMukherjee44/Aec-Library-Website#917]
### Feature description

The Resources page is probably the most important page of this website. The content is really good but the colours used don't make the content visually appealing. There's a pinch of blue used which doesn't really fit well with the brown theme. I would like to change a few colours and align some of the elements properly for a better finish.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by AishwaryaParab** [comment]
@SauravMukherjee44 could you please assign this issue to me?

**Comment by SauravMukherjee44** [comment]
Go for it!
