### ISSUE TITLE
Feature: Adding Icons

### ISSUE THREAD

**Issue by RishitaGangwal** [SauravMukherjee44/Aec-Library-Website#923]
### Feature description

![home](https://user-images.githubusercontent.com/88449534/193507557-6cdc2216-72fc-4c74-b007-22e89c58d6bc.jpeg)

Instead of writing Play and Pause on button, we can add icon of play and pause button. It will look more attractive to people.

Hey, @SauravMukherjee44
Please assign me with this as  an issue.

Thanks!

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by SauravMukherjee44** [comment]
Go for it! For support join our discord community: https://discord.com/servers/codein-community-831388874118660156

**Comment by JASKIRAT11011** [comment]
@SauravMukherjee44 plzz assign me this issue
