### ISSUE TITLE
Bug Report: The Hyperlink for 'Python' should take user to Python Documentation instead it takes to 'Full catalogs' and not specifically to Python Docs.

### ISSUE THREAD

**Issue by DhruvRathi2001** [SauravMukherjee44/Aec-Library-Website#928]
### Reproduction steps

I will  make the correct link  which goes to Python Documentation attached with the hyperlink.

### Expected behavior

Here in Python Section:

![first img](https://user-images.githubusercontent.com/94394117/193526390-b0f78198-eb5a-4df2-82ec-d014d7189047.png)

After clicking on 'Read more' it should take us to:

![correct image](https://user-images.githubusercontent.com/94394117/193526447-28e171c4-09db-435a-8035-de6815fe3325.png)

### Actual Behavior

Here in Python Section:

![first img](https://user-images.githubusercontent.com/94394117/193526390-b0f78198-eb5a-4df2-82ec-d014d7189047.png)

After clicking on 'Read more' it is taking us to 'Full catalogs' instead of 'Python Documentation':

![incorrect img](https://user-images.githubusercontent.com/94394117/193526640-e69cd188-9982-41ec-a277-069ec4302304.png)

@SauravMukherjee44  can you please assign this issue to me , I would love to fix it for HACKTOBERFEST.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by SauravMukherjee44** [comment]
Go for it! For support join our discord community: https://discord.com/servers/codein-community-831388874118660156
