### ISSUE TITLE
 Hover feature for Subscribe button

### ISSUE THREAD

**Issue by prakhar-1005** [SauravMukherjee44/Aec-Library-Website#929]
### Feature description

The Subscribe button has no hover feature in it which looks odd and seems like plain text instead of a button. Please allow me to add this feature in the site for enhanced user experience.

Screenshot:
![Screenshot (8)_LI](https://user-images.githubusercontent.com/94559623/193539907-7759f9ce-51f2-41eb-a514-3ab830a161a4.jpg)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by SauravMukherjee44** [comment]
Go for it!

**Comment by HamnaSiddiqui** [comment]
I would like to contribute to it

**Comment by amisha123prajapati** [comment]
I would like to contribute

**Comment by cmaguluri1305** [comment]
I would like to contribute, can any admin assign the tast to me?

**Comment by shrutimeg** [comment]
assign this issue to me

**Comment by Vivek-raj-64** [comment]
I can make this button hover, please assign it to me.
