### ISSUE TITLE
Feature:  Add Philosophy Section in select category of the issue box in the landing page

### ISSUE THREAD

**Issue by Jayaditya-Contributor** [SauravMukherjee44/Aec-Library-Website#931]
### Feature description

Since Philosophy is a major subject, it would be a great option to add a section for that , I think it is essential for a  Library in the Dropdown menu of category on landing page .

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by amisha123prajapati** [comment]
Hello @Jayaditya-Contributor,
I would like to contribute to it , could you please assign this issue to me!
