### ISSUE TITLE
Feature: Easy link option on email and phone number.

### ISSUE THREAD

**Issue by NateNear** [SauravMukherjee44/Aec-Library-Website#932]
### Feature description

I would like to add an easy copy option  on the email and phone number section  of the website, so that the user can copy the info by simply clicking on them. In addition I would like to add a "location" section between the email and phone number.
Please allow me to do the addressed changes.
![issue2](https://user-images.githubusercontent.com/92938055/193570848-70be00d5-17bf-4eac-b916-8ae12c90f4c8.PNG)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by SauravMukherjee44** [comment]
Go for it! For support join our discord community: https://discord.com/servers/codein-community-831388874118660156
