### ISSUE TITLE
Feature: Modify Login form UI

### ISSUE THREAD

**Issue by alvarule** [SauravMukherjee44/Aec-Library-Website#936]
### Feature description

I think the UI of login form and signup form should match with each other as it is of the same website. I want to make them match.
I will redesign the login form with reference to the signup form.
The current login form is as given below:
![Screenshot 2022-10-03 201034](https://user-images.githubusercontent.com/69820965/193605570-143caea3-a3fc-4561-b6d4-cf69b3f71b5c.png)

I want to make it like the signup form as below:
![Screenshot 2022-10-03 201051](https://user-images.githubusercontent.com/69820965/193605685-3853cfb4-0e16-4bcd-a63a-90cc9fac96b9.png)

Please assign me this task..

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by SauravMukherjee44** [comment]
Go for it!
