### ISSUE TITLE
Logo not linked to homepage on Contact Us page

### ISSUE THREAD

**Issue by ankittt20** [SauravMukherjee44/Aec-Library-Website#946]
### Reproduction steps

When I was going through the contact us page, I wanted to go back to the home page and I clicked on the logo and it didn't worked.

### Expected behavior

It should redirect me to the homepage.

### Actual Behavior

It is not linked to the homepage.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by henrymedeiros** [comment]
Tested on Brave Browser and It's working... Could you provide more details?

**Comment by ankittt20** [comment]
As you can see I clicked on the logo multiple times and nothing happened.

https://user-images.githubusercontent.com/92395053/193725083-1e36772c-c3f3-4393-ba8a-3aa8c969cfef.mp4

**Comment by ankittt20** [comment]
@SauravMukherjee44 can you please assign me this issue?

**Comment by SauravMukherjee44** [comment]
Go for it! For support join our discord community: https://discord.com/servers/codein-community-831388874118660156
