### ISSUE TITLE
Bug Report: Change year in footer

### ISSUE THREAD

**Issue by developer-diganta** [SauravMukherjee44/Aec-Library-Website#947]
### Reproduction steps

![image](https://user-images.githubusercontent.com/65999534/193676251-0406e6cf-77ca-41bc-a86c-fbb25c2b3478.png)
The year in footer is 2021. We can use javascript to keep it up to date.

### Expected behavior

It should be 2022

### Actual Behavior

It is 2021

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by developer-diganta** [comment]
If it seems legit, can I work on it?

**Comment by cmaguluri1305** [comment]
I want to contribute can anyone assign the task to me?

**Comment by pamudu** [comment]
Hi, I would like to work on this issue, can you assign this task for me?
