### ISSUE TITLE
Adding hover effect on links.

### ISSUE THREAD

**Issue by Garima-7** [SauravMukherjee44/Aec-Library-Website#95]
![Screenshot (452)](https://user-images.githubusercontent.com/83363645/135705649-00b6ad1d-b644-4ca4-84a0-4c32f47717f0.png)

Adding hover effect on links in navbar.
Something like this https://codepen.io/jstn/pen/zuDst

**Comment by Garima-7** [comment]
I want to work on this issue. Please assign it to me.

**Comment by omsali** [comment]
@SauravMukherjee44 Can I work on this issue

**Comment by yashsharma7128** [comment]
please assign this to me
