### ISSUE TITLE
Adding Programming language course in Resource page 

### ISSUE THREAD

**Issue by iamrahul8** [SauravMukherjee44/Aec-Library-Website#954]
### Feature description

I want to add some good courses in Resource Page 

> Along with correcting/replacing some images that are not working
![image](https://user-images.githubusercontent.com/72541381/193761792-dfd61718-ee23-46bd-96ff-5de32afcb403.png)

Please assign this issue to me under `hacktoberfest` @SauravMukherjee44 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by SauravMukherjee44** [comment]
Go for it! For support join our discord community: https://discord.com/servers/codein-community-831388874118660156
