### ISSUE TITLE
Change UI for Subscribe newsletter

### ISSUE THREAD

**Issue by KumarSashank** [SauravMukherjee44/Aec-Library-Website#958]
### Feature description

I saw the subscribe to the newsletter. That is looking old.

### Previous
![Screenshot 2022-10-04 at 10 27 1](https://user-images.githubusercontent.com/72877934/193886480-47abb1f5-cb08-4e3c-b639-7bbf53001c93.png)

### New Design
![subscribe](https://user-images.githubusercontent.com/72877934/193886633-13f36cd1-ce19-4ee7-ac99-3e5f10f46dad.png)

Inspired from loading animation of the website
![Screenshot 2022-10-04 at 10 24 1](https://user-images.githubusercontent.com/72877934/193886754-aaff799d-69ea-4c35-a135-27d2b25c78f9.png)

Assign me to change the design of subscribed newsletter option. #hacktoberfest 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by nabroleonx** [comment]
I want to work on this issue. Can you assign it to me?

**Comment by Chinmay-03** [comment]
@kamarSashank I would like to work on this
