### ISSUE TITLE
Improvements in the search section of resource.html

### ISSUE THREAD

**Issue by sshiwangi** [SauravMukherjee44/Aec-Library-Website#961]
### Feature description

The search for names section in the resource.html is looking bad. I would like to improve it.

Currently it is looking like this 

![aec libraray1](https://user-images.githubusercontent.com/77545230/194011416-d519d3ff-ba69-4092-ac62-1aa4a146fdc8.png)

It would look something like this

![aec library resource](https://user-images.githubusercontent.com/77545230/194010981-f0727177-f933-4f51-98d8-ca3dd4fd4c3f.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by sshiwangi** [comment]
@SauravMukherjee44 please assign me this issue under hacktoberfest.

**Comment by SauravMukherjee44** [comment]
Go for it! For support join our discord community: https://discord.com/servers/codein-community-831388874118660156
