### ISSUE TITLE
Improve search box

### ISSUE THREAD

**Issue by roshan2152** [SauravMukherjee44/Aec-Library-Website#965]
Typed words in the search box is not visible. @SauravMukherjee44 please assign me this, I can work on it.

<img width="671" alt="Screenshot 2022-10-05 at 7 34 46 PM" src="https://user-images.githubusercontent.com/111238532/194080654-7a3700ce-6b27-466c-b22f-07f61459c6c6.png">

**Comment by SauravMukherjee44** [comment]
Go for it! For support join our discord community: https://discord.com/servers/codein-community-831388874118660156

**Comment by roshan2152** [comment]
> Go for it! For support join our discord community: https://discord.com/servers/codein-community-831388874118660156

Thanks @SauravMukherjee44, I'm already a member of code-in community

**Comment by Mrsingh782** [comment]
Can you please assist me this issue ? @SauravMukherjee44

**Comment by arneja-arnav** [comment]
@SauravMukherjee44 no one has closed this issue yet. Is it fine if you assign it to me?

**Comment by Ashutoshsoni1** [comment]
@SauravMukherjee44 
Please assign this issue to me.

**Comment by maneet057** [comment]
I would like to work on this issue. Can you please assign it to me?
