### ISSUE TITLE
Feature: Improve the UI of the High Score section of the Quiz and fix its responsiveness.

### ISSUE THREAD

**Issue by surbhi400** [SauravMukherjee44/Aec-Library-Website#995]
### Feature description

The UI of the high score page of the quiz is not looking good as well as it is not responsive. 
![improve UI](https://user-images.githubusercontent.com/77582783/194457474-f2f39800-291e-455a-abfe-8582367447bc.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by surbhi400** [comment]
@SauravMukherjee44 can you please assign me this issue. I would like to work on it.

**Comment by SauravMukherjee44** [comment]
Go for it!
